package scanner

import (
	"regexp"

	"github.com/security-monitoring-toolkit/internal/common"
)

type ScanRule struct {
	Name            string
	Description     string
	Pattern         *regexp.Regexp
	Severity        common.SeverityLevel
	Category        string
	Remediation     string
	Enabled         bool
	ContextLines    int
}

var DefaultRules = []*ScanRule{
	{
		Name:        "aws-access-key-id",
		Description: "AWS Access Key ID detected",
		Pattern:     regexp.MustCompile(`AKIA[0-9A-Z]{16}`),
		Severity:    common.SeverityCritical,
		Category:    "cloud-credentials",
		Remediation: "Remove this hardcoded AWS access key and use environment variables or AWS IAM roles instead.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "aws-secret-access-key",
		Description: "AWS Secret Access Key detected",
		Pattern:     regexp.MustCompile(`(?:aws)?_?(?:secret)_?(?:access)?_?(?:key)?\s*[:=]\s*["']?[A-Za-z0-9/\+=]{40}["']?`),
		Severity:    common.SeverityCritical,
		Category:    "cloud-credentials",
		Remediation: "Remove this hardcoded AWS secret and use environment variables or AWS IAM roles instead.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "github-pat",
		Description: "GitHub Personal Access Token detected",
		Pattern:     regexp.MustCompile(`ghp_[0-9a-zA-Z]{36}`),
		Severity:    common.SeverityCritical,
		Category:    "cloud-credentials",
		Remediation: "Revoke this token immediately and use environment variables or GitHub secrets instead.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "github-oauth",
		Description: "GitHub OAuth Token detected",
		Pattern:     regexp.MustCompile(`gho_[0-9a-zA-Z]{36}`),
		Severity:    common.SeverityCritical,
		Category:    "cloud-credentials",
		Remediation: "Revoke this token immediately.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "slack-webhook-url",
		Description: "Slack Webhook URL detected",
		Pattern:     regexp.MustCompile(`https://hooks.slack.com/services/[A-Z0-9]+/[A-Z0-9]+/[A-Za-z0-9]+`),
		Severity:    common.SeverityHigh,
		Category:    "webhook-secrets",
		Remediation: "Move this webhook URL to environment variables.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "hardcoded-password",
		Description: "Hardcoded password detected",
		Pattern:     regexp.MustCompile(`(?i)(?:password|passwd|pwd|pass)\s*[:=]\s*["'][^"']{5,}["']`),
		Severity:    common.SeverityHigh,
		Category:    "hardcoded-secrets",
		Remediation: "Replace hardcoded password with environment variable or secret management service.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "api-key-generic",
		Description: "Potential API Key detected",
		Pattern:     regexp.MustCompile(`(?i)(?:api[-_]?key|apikey|api[-_]?token|apitoken)\s*[:=]\s*["'][a-zA-Z0-9-_]{16,}["']`),
		Severity:    common.SeverityMedium,
		Category:    "api-keys",
		Remediation: "Review and move to environment variables if this is a real API key.",
		Enabled:     true,
		ContextLines: 2,
	},
	{
		Name:        "private-ssh-key",
		Description: "Private SSH Key detected",
		Pattern:     regexp.MustCompile(`-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----`),
		Severity:    common.SeverityCritical,
		Category:    "cryptographic-keys",
		Remediation: "Private SSH keys should never be committed. Remove this file and use proper key management.",
		Enabled:     true,
		ContextLines: 3,
	},
	{
		Name:        "pgp-private-key",
		Description: "PGP Private Key detected",
		Pattern:     regexp.MustCompile(`-----BEGIN PGP PRIVATE KEY BLOCK-----`),
		Severity:    common.SeverityCritical,
		Category:    "cryptographic-keys",
		Remediation: "PGP private keys should never be committed. Remove immediately.",
		Enabled:     true,
		ContextLines: 3,
	},
	{
		Name:        "database-url",
		Description: "Database connection URL with credentials detected",
		Pattern:     regexp.MustCompile(`(?:postgres|mysql|mongodb|redis)://[^:]+:[^@]+@[^\s"'>]+`),
		Severity:    common.SeverityHigh,
		Category:    "database-credentials",
		Remediation: "Extract credentials from the URL and use environment variables instead.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "bearer-token",
		Description: "Bearer Token detected",
		Pattern:     regexp.MustCompile(`(?i)bearer\s+[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*`),
		Severity:    common.SeverityHigh,
		Category:    "api-keys",
		Remediation: "This appears to be a JWT or OAuth token. Do not hardcode tokens in source code.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "heroku-api-key",
		Description: "Heroku API Key detected",
		Pattern:     regexp.MustCompile(`[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`),
		Severity:    common.SeverityHigh,
		Category:    "cloud-credentials",
		Remediation: "Revoke this Heroku API key and use environment variables.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "stripe-api-key",
		Description: "Stripe API Key detected",
		Pattern:     regexp.MustCompile(`(?:sk|pk)_(?:test|live)_[A-Za-z0-9]{24,}`),
		Severity:    common.SeverityCritical,
		Category:    "payment-credentials",
		Remediation: "Revoke this Stripe API key immediately and use environment variables.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "twilio-api-key",
		Description: "Twilio API Key detected",
		Pattern:     regexp.MustCompile(`SK[0-9a-fA-F]{32}`),
		Severity:    common.SeverityHigh,
		Category:    "cloud-credentials",
		Remediation: "Revoke this Twilio API key and use environment variables.",
		Enabled:     true,
		ContextLines: 1,
	},
	{
		Name:        "google-api-key",
		Description: "Google API Key detected",
		Pattern:     regexp.MustCompile(`AIza[0-9A-Za-z_-]{35}`),
		Severity:    common.SeverityHigh,
		Category:    "cloud-credentials",
		Remediation: "Restrict this API key by IP or HTTP referrer in Google Cloud Console.",
		Enabled:     true,
		ContextLines: 1,
	},
}

var DefaultIgnorePatterns = []string{
	".git",
	".svn",
	".hg",
	"node_modules",
	"vendor",
	"dist",
	"build",
	"target",
	".idea",
	".vscode",
	"*.min.js",
	"*.min.css",
	"*.pyc",
	"*.class",
	"*.exe",
	"*.dll",
	"*.so",
	"*.dylib",
	"*.zip",
	"*.tar.gz",
	"*.tar",
	"*.rar",
	"*.7z",
	"*.gif",
	"*.jpg",
	"*.jpeg",
	"*.png",
	"*.ico",
	"*.svg",
	"*.ttf",
	"*.otf",
	"*.woff",
	"*.woff2",
	"*.eot",
	"*.pdf",
	"*.doc",
	"*.docx",
	"*.xls",
	"*.xlsx",
	"*.ppt",
	"*.pptx",
	"test-fixtures",
	"testdata",
	"examples",
	"sample-keys",
}
