export const questionBank = {
    name: "初中数学题库",
    version: "2.0.0",
    subjects: ["初中数学"],
    topics: ["代数", "几何"],
    fixedScores: {
        "选择题": 3,
        "填空题": 4,
        "解答题": 10
    },
    questions: [
        { id: "A-C-001", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "计算 2 + 3 的结果是？", options: ["4", "5", "6", "7"], answer: "B", knowledgePoint: "有理数的加法" },
        { id: "A-C-002", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "计算 (-1) + 2 的结果是？", options: ["1", "-1", "3", "-3"], answer: "A", knowledgePoint: "有理数的加法" },
        { id: "A-C-003", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "方程 x + 1 = 5 的解是？", options: ["x = 3", "x = 4", "x = 5", "x = 6"], answer: "B", knowledgePoint: "一元一次方程" },
        { id: "A-C-004", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 3, question: "方程 2x = 6 的解是？", options: ["x = 2", "x = 3", "x = 4", "x = 12"], answer: "B", knowledgePoint: "一元一次方程" },
        { id: "A-C-005", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "化简 2a + 3a 的结果是？", options: ["5a", "6a", "5a²", "6a²"], answer: "A", knowledgePoint: "合并同类项" },
        { id: "A-C-006", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 3, question: "化简 -3x + 5x 的结果是？", options: ["2x", "-2x", "8x", "-8x"], answer: "A", knowledgePoint: "合并同类项" },
        { id: "A-C-007", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "计算 2³ 的值是？", options: ["6", "8", "9", "16"], answer: "B", knowledgePoint: "有理数的乘方" },
        { id: "A-C-008", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 3, question: "计算 (-2)² 的值是？", options: ["-4", "4", "-8", "8"], answer: "B", knowledgePoint: "有理数的乘方" },
        { id: "A-C-009", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 3, question: "方程 2x + 1 = 7 的解是？", options: ["x = 2", "x = 3", "x = 4", "x = 5"], answer: "B", knowledgePoint: "一元一次方程" },
        { id: "A-C-010", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 3, question: "方程 3(x - 1) = 6 的解是？", options: ["x = 2", "x = 3", "x = 4", "x = 5"], answer: "B", knowledgePoint: "一元一次方程" },
        { id: "A-C-011", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 3, question: "因式分解 x² - 9 的结果是？", options: ["(x-3)²", "(x+3)²", "(x-3)(x+3)", "(x-9)(x+1)"], answer: "C", knowledgePoint: "平方差公式" },
        { id: "A-C-012", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 3, question: "因式分解 4x² - 1 的结果是？", options: ["(2x-1)²", "(2x+1)²", "(2x-1)(2x+1)", "(4x-1)(x+1)"], answer: "C", knowledgePoint: "平方差公式" },
        { id: "A-C-013", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 3, question: "化简 √9 的结果是？", options: ["2", "3", "4", "9"], answer: "B", knowledgePoint: "算术平方根" },
        { id: "A-C-014", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 3, question: "化简 √25 的结果是？", options: ["4", "5", "6", "25"], answer: "B", knowledgePoint: "算术平方根" },
        { id: "A-C-015", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 3, question: "方程 x² - 4 = 0 的解是？", options: ["x = 2", "x = -2", "x = ±2", "无解"], answer: "C", knowledgePoint: "一元二次方程" },
        { id: "A-C-016", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 3, question: "方程 x² - 5x + 6 = 0 的解是？", options: ["x = 2", "x = 3", "x = 2 或 x = 3", "无解"], answer: "C", knowledgePoint: "一元二次方程" },
        { id: "A-C-017", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 3, question: "函数 y = 2x + 1 经过哪个点？", options: ["(0, 0)", "(0, 1)", "(1, 0)", "(1, 1)"], answer: "B", knowledgePoint: "一次函数" },
        { id: "A-C-018", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 3, question: "函数 y = -x + 2 经过哪个点？", options: ["(0, 2)", "(2, 0)", "以上都对", "以上都不对"], answer: "C", knowledgePoint: "一次函数" },
        { id: "A-C-019", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 3, question: "计算 5 - 2 的结果是？", options: ["2", "3", "4", "5"], answer: "B", knowledgePoint: "有理数的减法" },
        { id: "A-C-020", type: "选择题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 3, question: "计算 (-3) - 2 的结果是？", options: ["-5", "-1", "1", "5"], answer: "A", knowledgePoint: "有理数的减法" },

        { id: "G-C-001", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 3, question: "三角形的内角和是多少度？", options: ["90°", "180°", "270°", "360°"], answer: "B", knowledgePoint: "三角形内角和" },
        { id: "G-C-002", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 3, question: "四边形的内角和是多少度？", options: ["90°", "180°", "270°", "360°"], answer: "D", knowledgePoint: "四边形内角和" },
        { id: "G-C-003", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 3, question: "正方形有几条对称轴？", options: ["2条", "3条", "4条", "8条"], answer: "C", knowledgePoint: "轴对称图形" },
        { id: "G-C-004", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 3, question: "圆有几条对称轴？", options: ["1条", "2条", "4条", "无数条"], answer: "D", knowledgePoint: "轴对称图形" },
        { id: "G-C-005", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 3, question: "下列哪组线段可以组成三角形？", options: ["1, 2, 3", "2, 3, 4", "1, 1, 3", "2, 2, 5"], answer: "B", knowledgePoint: "三角形三边关系" },
        { id: "G-C-006", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 3, question: "下列哪组线段不能组成三角形？", options: ["3, 4, 5", "5, 5, 5", "1, 2, 4", "6, 8, 10"], answer: "C", knowledgePoint: "三角形三边关系" },
        { id: "G-C-007", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 3, question: "下列哪个是中心对称图形？", options: ["等边三角形", "等腰三角形", "平行四边形", "正五边形"], answer: "C", knowledgePoint: "中心对称图形" },
        { id: "G-C-008", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 3, question: "下列哪个既是轴对称又是中心对称？", options: ["等边三角形", "矩形", "等腰梯形", "正五边形"], answer: "B", knowledgePoint: "对称图形" },
        { id: "G-C-009", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 3, question: "直角三角形直角边为3和4，斜边为？", options: ["5", "6", "7", "12"], answer: "A", knowledgePoint: "勾股定理" },
        { id: "G-C-010", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 3, question: "直角三角形斜边为5，一条直角边为3，另一条为？", options: ["2", "3", "4", "6"], answer: "C", knowledgePoint: "勾股定理" },
        { id: "G-C-011", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 3, question: "平行四边形对角线性质是？", options: ["相等", "互相垂直", "互相平分", "垂直且平分"], answer: "C", knowledgePoint: "平行四边形性质" },
        { id: "G-C-012", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 3, question: "矩形对角线性质是？", options: ["相等", "互相平分", "相等且互相平分", "垂直"], answer: "C", knowledgePoint: "矩形性质" },
        { id: "G-C-013", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 3, question: "圆的周长公式是？", options: ["C = πr", "C = 2πr", "C = πr²", "C = 2πr²"], answer: "B", knowledgePoint: "圆的周长" },
        { id: "G-C-014", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 3, question: "圆的面积公式是？", options: ["S = πr", "S = 2πr", "S = πr²", "S = 2πr²"], answer: "C", knowledgePoint: "圆的面积" },
        { id: "G-C-015", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 3, question: "相似三角形面积比是相似比的？", options: ["1倍", "2倍", "3倍", "平方倍"], answer: "D", knowledgePoint: "相似三角形" },
        { id: "G-C-016", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 3, question: "全等三角形面积比是？", options: ["1:1", "1:2", "2:1", "平方比"], answer: "A", knowledgePoint: "全等三角形" },
        { id: "G-C-017", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 3, question: "直角三角形的直角个数是？", options: ["1个", "2个", "3个", "不确定"], answer: "A", knowledgePoint: "直角三角形" },
        { id: "G-C-018", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 3, question: "等边三角形每个角是多少度？", options: ["30°", "60°", "90°", "180°"], answer: "B", knowledgePoint: "等边三角形" },
        { id: "G-C-019", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 3, question: "不能判定三角形全等的是？", options: ["SSS", "SAS", "ASA", "SSA"], answer: "D", knowledgePoint: "全等判定" },
        { id: "G-C-020", type: "选择题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 3, question: "能判定三角形全等的是？", options: ["AAA", "SSA", "AAS", "以上都不能"], answer: "C", knowledgePoint: "全等判定" },

        { id: "A-F-001", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 4, question: "计算：3 + 5 = ______", answer: "8", knowledgePoint: "有理数的加法" },
        { id: "A-F-002", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 4, question: "计算：(-2) + 3 = ______", answer: "1", knowledgePoint: "有理数的加法" },
        { id: "A-F-003", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 4, question: "方程 x + 2 = 7 的解是 x = ______", answer: "5", knowledgePoint: "一元一次方程" },
        { id: "A-F-004", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 4, question: "方程 3x = 12 的解是 x = ______", answer: "4", knowledgePoint: "一元一次方程" },
        { id: "A-F-005", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 4, question: "计算：2³ = ______", answer: "8", knowledgePoint: "有理数的乘方" },
        { id: "A-F-006", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 4, question: "计算：(-3)² = ______", answer: "9", knowledgePoint: "有理数的乘方" },
        { id: "A-F-007", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 4, question: "因式分解：x² - 4 = ______", answer: "(x-2)(x+2)", knowledgePoint: "平方差公式" },
        { id: "A-F-008", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 4, question: "因式分解：x² - 6x + 9 = ______", answer: "(x-3)²", knowledgePoint: "完全平方公式" },
        { id: "A-F-009", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 4, question: "若 |x| = 3，则 x = ______", answer: "±3", knowledgePoint: "绝对值" },
        { id: "A-F-010", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 4, question: "若 |x - 1| = 2，则 x = ______", answer: "3 或 -1", knowledgePoint: "绝对值" },
        { id: "A-F-011", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 4, question: "函数 y = √(x - 2) 的定义域是 ______", answer: "x ≥ 2", knowledgePoint: "函数定义域" },
        { id: "A-F-012", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 4, question: "函数 y = 1/(x - 1) 的定义域是 ______", answer: "x ≠ 1", knowledgePoint: "函数定义域" },
        { id: "A-F-013", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 4, question: "化简：√16 = ______", answer: "4", knowledgePoint: "算术平方根" },
        { id: "A-F-014", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 4, question: "化简：√36 = ______", answer: "6", knowledgePoint: "算术平方根" },
        { id: "A-F-015", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 4, question: "计算：10 - 4 = ______", answer: "6", knowledgePoint: "有理数的减法" },
        { id: "A-F-016", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 4, question: "计算：(-5) - 2 = ______", answer: "-7", knowledgePoint: "有理数的减法" },
        { id: "A-F-017", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 4, question: "若 a + b = 5，ab = 6，则 a² + b² = ______", answer: "13", knowledgePoint: "完全平方公式" },
        { id: "A-F-018", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 4, question: "若 a - b = 3，ab = 10，则 a² + b² = ______", answer: "29", knowledgePoint: "完全平方公式" },
        { id: "A-F-019", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 4, question: "方程 2x - 4 = 0 的解是 x = ______", answer: "2", knowledgePoint: "一元一次方程" },
        { id: "A-F-020", type: "填空题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 4, question: "方程 4(x + 1) = 12 的解是 x = ______", answer: "2", knowledgePoint: "一元一次方程" },

        { id: "G-F-001", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 4, question: "直角三角形两锐角之和为 ______ 度", answer: "90", knowledgePoint: "直角三角形" },
        { id: "G-F-002", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 4, question: "等腰三角形两底角 ______", answer: "相等", knowledgePoint: "等腰三角形" },
        { id: "G-F-003", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 4, question: "边长为4的正方形面积是 ______", answer: "16", knowledgePoint: "正方形面积" },
        { id: "G-F-004", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 4, question: "边长为5的正方形周长是 ______", answer: "20", knowledgePoint: "正方形周长" },
        { id: "G-F-005", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 4, question: "圆半径为2，面积为 ______", answer: "4π", knowledgePoint: "圆的面积" },
        { id: "G-F-006", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 4, question: "圆半径为3，周长为 ______", answer: "6π", knowledgePoint: "圆的周长" },
        { id: "G-F-007", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 4, question: "等边三角形每个内角为 ______ 度", answer: "60", knowledgePoint: "等边三角形" },
        { id: "G-F-008", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 4, question: "正五边形内角和是 ______ 度", answer: "540", knowledgePoint: "多边形内角和" },
        { id: "G-F-009", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 4, question: "等腰三角形一个角为70°，顶角为 ______ 度", answer: "70 或 40", knowledgePoint: "等腰三角形" },
        { id: "G-F-010", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 4, question: "等腰三角形一个角为100°，顶角为 ______ 度", answer: "100", knowledgePoint: "等腰三角形" },
        { id: "G-F-011", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 4, question: "三角形有 ______ 条边", answer: "3", knowledgePoint: "三角形定义" },
        { id: "G-F-012", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 4, question: "四边形有 ______ 个内角", answer: "4", knowledgePoint: "四边形定义" },
        { id: "G-F-013", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 4, question: "正六边形内角和是 ______ 度", answer: "720", knowledgePoint: "多边形内角和" },
        { id: "G-F-014", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 4, question: "正八边形内角和是 ______ 度", answer: "1080", knowledgePoint: "多边形内角和" },
        { id: "G-F-015", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 4, question: "平行四边形对边 ______ 且相等", answer: "平行", knowledgePoint: "平行四边形" },
        { id: "G-F-016", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 4, question: "矩形四个角都是 ______ 角", answer: "直", knowledgePoint: "矩形" },
        { id: "G-F-017", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 4, question: "圆有 ______ 条半径", answer: "无数", knowledgePoint: "圆" },
        { id: "G-F-018", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 4, question: "直径是半径的 ______ 倍", answer: "2", knowledgePoint: "圆" },
        { id: "G-F-019", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 4, question: "菱形对角线互相 ______", answer: "垂直", knowledgePoint: "菱形" },
        { id: "G-F-020", type: "填空题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 4, question: "正方形对角线 ______ 且相等", answer: "垂直", knowledgePoint: "正方形" },

        { id: "A-A-001", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 10, question: "计算：15 + 27 - 8", answer: "34", knowledgePoint: "有理数的加减" },
        { id: "A-A-002", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 10, question: "计算：(-12) + 18 - (-5)", answer: "11", knowledgePoint: "有理数的加减" },
        { id: "A-A-003", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 10, question: "解方程：3x + 2 = 11", answer: "x = 3", knowledgePoint: "一元一次方程" },
        { id: "A-A-004", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 10, question: "解方程：5(x - 2) = 15", answer: "x = 5", knowledgePoint: "一元一次方程" },
        { id: "A-A-005", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 10, question: "化简：(2x + 3y) + (x - 2y)", answer: "3x + y", knowledgePoint: "整式的加减" },
        { id: "A-A-006", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 10, question: "化简：3(a + 2b) - 2(a - b)", answer: "a + 8b", knowledgePoint: "整式的加减" },
        { id: "A-A-007", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 10, question: "因式分解：x² - 16", answer: "(x-4)(x+4)", knowledgePoint: "平方差公式" },
        { id: "A-A-008", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 10, question: "因式分解：9x² - 25", answer: "(3x-5)(3x+5)", knowledgePoint: "平方差公式" },
        { id: "A-A-009", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 10, question: "解方程：x² - 9 = 0", answer: "x = ±3", knowledgePoint: "一元二次方程" },
        { id: "A-A-010", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 10, question: "解方程：x² - 7x + 10 = 0", answer: "x = 2 或 x = 5", knowledgePoint: "一元二次方程" },
        { id: "A-A-011", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 10, question: "计算：(-3) × 4 ÷ 2", answer: "-6", knowledgePoint: "有理数的乘除" },
        { id: "A-A-012", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 10, question: "计算：(-24) ÷ (-6) × 3", answer: "12", knowledgePoint: "有理数的乘除" },
        { id: "A-A-013", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 10, question: "化简：(a + b)² - (a - b)²", answer: "4ab", knowledgePoint: "完全平方公式" },
        { id: "A-A-014", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 10, question: "化简：(x + 2)(x - 2) + 4", answer: "x²", knowledgePoint: "平方差公式" },
        { id: "A-A-015", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "基础", score: 10, question: "求函数 y = 2x + 1 在 x = 3 时的值", answer: "7", knowledgePoint: "一次函数" },
        { id: "A-A-016", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 3, subDifficulty: "进阶", score: 10, question: "已知 y = kx + b 经过 (0, 1) 和 (1, 3)，求 k", answer: "2", knowledgePoint: "一次函数" },
        { id: "A-A-017", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "基础", score: 10, question: "方程 2x - 5 = 3 的解是？", answer: "x = 4", knowledgePoint: "一元一次方程" },
        { id: "A-A-018", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 1, subDifficulty: "进阶", score: 10, question: "方程 4x + 7 = 2x + 11 的解是？", answer: "x = 2", knowledgePoint: "一元一次方程" },
        { id: "A-A-019", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "基础", score: 10, question: "计算：√4 + √9", answer: "5", knowledgePoint: "算术平方根" },
        { id: "A-A-020", type: "解答题", subject: "初中数学", topic: "代数", difficulty: 2, subDifficulty: "进阶", score: 10, question: "计算：√16 - √25", answer: "-1", knowledgePoint: "算术平方根" },

        { id: "G-A-001", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 10, question: "求边长为6的正方形周长", answer: "24", knowledgePoint: "正方形周长" },
        { id: "G-A-002", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 10, question: "求边长为7的正方形面积", answer: "49", knowledgePoint: "正方形面积" },
        { id: "G-A-003", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 10, question: "三角形两个角分别为60°和70°，第三个角是？", answer: "50°", knowledgePoint: "三角形内角和" },
        { id: "G-A-004", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 10, question: "直角三角形一个锐角为35°，另一个锐角是？", answer: "55°", knowledgePoint: "直角三角形" },
        { id: "G-A-005", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 10, question: "直角三角形直角边为5和12，求斜边", answer: "13", knowledgePoint: "勾股定理" },
        { id: "G-A-006", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 10, question: "直角三角形斜边为13，一条直角边为5，求另一条", answer: "12", knowledgePoint: "勾股定理" },
        { id: "G-A-007", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 10, question: "圆半径为4，求周长", answer: "8π", knowledgePoint: "圆的周长" },
        { id: "G-A-008", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 10, question: "圆半径为5，求面积", answer: "25π", knowledgePoint: "圆的面积" },
        { id: "G-A-009", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 10, question: "相似三角形相似比为2:3，面积比是？", answer: "4:9", knowledgePoint: "相似三角形" },
        { id: "G-A-010", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 10, question: "相似三角形面积比为1:4，周长比是？", answer: "1:2", knowledgePoint: "相似三角形" },
        { id: "G-A-011", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 10, question: "长方形长为8，宽为5，求周长", answer: "26", knowledgePoint: "长方形周长" },
        { id: "G-A-012", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 10, question: "长方形长为8，宽为5，求面积", answer: "40", knowledgePoint: "长方形面积" },
        { id: "G-A-013", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 10, question: "等边三角形边长为6，求周长", answer: "18", knowledgePoint: "等边三角形" },
        { id: "G-A-014", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 10, question: "平行四边形底为8，高为5，求面积", answer: "40", knowledgePoint: "平行四边形" },
        { id: "G-A-015", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "基础", score: 10, question: "圆直径为10，求周长", answer: "10π", knowledgePoint: "圆的周长" },
        { id: "G-A-016", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 3, subDifficulty: "进阶", score: 10, question: "圆直径为10，求面积", answer: "25π", knowledgePoint: "圆的面积" },
        { id: "G-A-017", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "基础", score: 10, question: "三角形三边为3、4、5，这是什么三角形？", answer: "直角三角形", knowledgePoint: "三角形分类" },
        { id: "G-A-018", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 1, subDifficulty: "进阶", score: 10, question: "三角形三边为5、5、5，这是什么三角形？", answer: "等边三角形", knowledgePoint: "三角形分类" },
        { id: "G-A-019", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "基础", score: 10, question: "菱形边长为5，求周长", answer: "20", knowledgePoint: "菱形" },
        { id: "G-A-020", type: "解答题", subject: "初中数学", topic: "几何", difficulty: 2, subDifficulty: "进阶", score: 10, question: "梯形上底3，下底7，高4，求面积", answer: "20", knowledgePoint: "梯形" }
    ]
};
