# Generated by Django 4.2.7 on 2026-05-03 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("contract_expiry", "合同到期提醒"),
                            ("rent_payment", "租金支付提醒"),
                            ("billing_due", "账单到期提醒"),
                            ("custom", "自定义提醒"),
                        ],
                        max_length=30,
                        verbose_name="提醒类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="提醒标题")),
                ("message", models.TextField(verbose_name="提醒内容")),
                ("scheduled_date", models.DateField(verbose_name="预定提醒日期")),
                (
                    "scheduled_time",
                    models.TimeField(default="09:00:00", verbose_name="预定提醒时间"),
                ),
                ("channels", models.JSONField(default=list, verbose_name="提醒渠道")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="是否重复提醒"),
                ),
                (
                    "recurring_pattern",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="重复模式"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="是否已发送"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="contracts.rentalcontract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒",
                "verbose_name_plural": "提醒管理",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("app", "应用内通知"),
                            ("sms", "短信"),
                            ("email", "邮件"),
                        ],
                        max_length=20,
                        verbose_name="发送渠道",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("read", "已阅读"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="接收者")),
                (
                    "message_content",
                    models.TextField(blank=True, null=True, verbose_name="消息内容"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reminders.reminder",
                        verbose_name="提醒",
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒日志",
                "verbose_name_plural": "提醒日志管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
