# Generated by Django 4.2.7 on 2026-05-03 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="房屋名称")),
                ("address", models.CharField(max_length=500, verbose_name="详细地址")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "公寓"),
                            ("house", "住宅"),
                            ("studio", "单间"),
                            ("loft", "loft"),
                            ("other", "其他"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="房屋类型",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="面积(㎡)",
                    ),
                ),
                (
                    "rooms",
                    models.IntegerField(blank=True, null=True, verbose_name="房间数"),
                ),
                (
                    "bathrooms",
                    models.IntegerField(blank=True, null=True, verbose_name="卫生间数"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="房屋描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "房屋",
                "verbose_name_plural": "房屋管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="紧急联系人"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="紧急联系电话",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "房客",
                "verbose_name_plural": "房客管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="合同编号"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="月租金(元)"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="押金(元)"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="月付", max_length=50, verbose_name="付款方式"
                    ),
                ),
                (
                    "payment_day",
                    models.IntegerField(default=1, verbose_name="每月付款日"),
                ),
                (
                    "utilities_included",
                    models.BooleanField(
                        default=False, verbose_name="水电费包含在房租中"
                    ),
                ),
                (
                    "water_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=5,
                        verbose_name="水费单价(元/吨)",
                    ),
                ),
                (
                    "electricity_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.85,
                        max_digits=5,
                        verbose_name="电费单价(元/度)",
                    ),
                ),
                (
                    "gas_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=2.8,
                        max_digits=5,
                        null=True,
                        verbose_name="燃气费单价(元/立方米)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "有效"),
                            ("expired", "已到期"),
                            ("terminated", "已终止"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="合同状态",
                    ),
                ),
                (
                    "terms",
                    models.TextField(blank=True, null=True, verbose_name="合同条款"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="房东",
                    ),
                ),
                (
                    "property_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="contracts.property",
                        verbose_name="房屋",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_contracts",
                        to="contracts.tenant",
                        verbose_name="房客",
                    ),
                ),
            ],
            options={
                "verbose_name": "租房合同",
                "verbose_name_plural": "租房合同管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("water", "水表"),
                            ("electricity", "电表"),
                            ("gas", "燃气表"),
                        ],
                        max_length=20,
                        verbose_name="表类型",
                    ),
                ),
                ("reading_date", models.DateField(verbose_name="抄表日期")),
                (
                    "previous_reading",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="上期读数"
                    ),
                ),
                (
                    "current_reading",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="本期读数"
                    ),
                ),
                (
                    "usage",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="用量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="单价"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="总金额"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="contracts.rentalcontract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "抄表记录",
                "verbose_name_plural": "抄表记录管理",
                "ordering": ["-reading_date"],
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="文档名称")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "合同原件"),
                            ("addendum", "补充协议"),
                            ("receipt", "收据"),
                            ("other", "其他"),
                        ],
                        default="contract",
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="contracts/documents/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "ocr_processed",
                    models.BooleanField(default=False, verbose_name="已进行OCR处理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="contracts.rentalcontract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同文档",
                "verbose_name_plural": "合同文档管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
