/**
 * Decorators for ORM model definition
 * 
 * Provides @Table and @Column decorators for defining
 * database models using TypeScript decorators.
 */

import { ColumnType, addColumnMetadata, setTableMetadata } from './metadata';

/**
 * Table decorator options
 */
export interface TableOptions {
  name?: string;
  schema?: string;
}

/**
 * Column decorator options
 */
export interface ColumnOptions {
  name?: string;
  type?: ColumnType;
  nullable?: boolean;
  primary?: boolean;
  generated?: boolean;
  unique?: boolean;
  default?: any;
  length?: number;
  precision?: number;
  scale?: number;
}

/**
 * Primary key column options
 */
export interface PrimaryKeyOptions extends ColumnOptions {
  autoIncrement?: boolean;
}

/**
 * @Table decorator
 * 
 * Marks a class as a database table model.
 * 
 * @example
 * ```typescript
 * @Table('users')
 * class User {
 *   // ...
 * }
 * ```
 */
export function Table(name?: string): ClassDecorator;
export function Table(options?: TableOptions): ClassDecorator;
export function Table(nameOrOptions?: string | TableOptions): ClassDecorator {
  return function (target: Function) {
    let tableName: string;
    let schema: string | undefined;
    
    if (typeof nameOrOptions === 'string') {
      tableName = nameOrOptions;
    } else if (nameOrOptions && typeof nameOrOptions === 'object') {
      tableName = nameOrOptions.name || target.name;
      schema = nameOrOptions.schema;
    } else {
      tableName = target.name;
    }
    
    setTableMetadata(target, {
      name: tableName,
      schema,
    });
  };
}

/**
 * @Column decorator
 * 
 * Marks a class property as a database column.
 * 
 * @example
 * ```typescript
 * @Column({ type: ColumnType.String, length: 255 })
 * name: string;
 * ```
 */
export function Column(options?: ColumnOptions): PropertyDecorator {
  return function (target: Object, propertyName: string | symbol) {
    const propName = String(propertyName);
    
    // Get type from reflect metadata
    const reflectedType = Reflect.getMetadata('design:type', target, propertyName);
    
    let columnType: ColumnType = ColumnType.String;
    
    // Infer type from reflected metadata
    if (reflectedType) {
      if (reflectedType === String) {
        columnType = ColumnType.String;
      } else if (reflectedType === Number) {
        columnType = ColumnType.Number;
      } else if (reflectedType === Boolean) {
        columnType = ColumnType.Boolean;
      } else if (reflectedType === Date) {
        columnType = ColumnType.DateTime;
      }
    }
    
    // Override with explicit options
    if (options?.type) {
      columnType = options.type;
    }
    
    const columnName = options?.name || propName;
    
    addColumnMetadata(target, propName, {
      propertyName: propName,
      columnName: columnName,
      type: columnType,
      isNullable: options?.nullable ?? true,
      isPrimary: options?.primary ?? false,
      isGenerated: options?.generated ?? false,
      isUnique: options?.unique ?? false,
      default: options?.default,
      length: options?.length,
      precision: options?.precision,
      scale: options?.scale,
    });
  };
}

/**
 * @PrimaryKey decorator
 * 
 * Marks a property as the primary key column.
 * 
 * @example
 * ```typescript
 * @PrimaryKey({ autoIncrement: true })
 * id: number;
 * ```
 */
export function PrimaryKey(options?: PrimaryKeyOptions): PropertyDecorator {
  return Column({
    ...options,
    primary: true,
    generated: options?.autoIncrement ?? true,
    nullable: false,
  });
}

/**
 * @Generated decorator
 * 
 * Marks a column as auto-generated by the database.
 */
export function Generated(): PropertyDecorator {
  return function (target: Object, propertyName: string | symbol) {
    // Get existing column metadata and modify it
    const propName = String(propertyName);
    const existingMetadata = Reflect.getMetadata('orm:column', target, propertyName);
    
    if (existingMetadata) {
      existingMetadata.isGenerated = true;
    }
  };
}

/**
 * @Unique decorator
 * 
 * Marks a column as having a unique constraint.
 */
export function Unique(): PropertyDecorator {
  return function (target: Object, propertyName: string | symbol) {
    const propName = String(propertyName);
    const existingMetadata = Reflect.getMetadata('orm:column', target, propertyName);
    
    if (existingMetadata) {
      existingMetadata.isUnique = true;
    }
  };
}

// Re-export ColumnType for convenience
export { ColumnType } from './metadata';
