# Generated by Django 4.2.7 on 2026-05-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("rent", "房租"),
                            ("water", "水费"),
                            ("electricity", "电费"),
                            ("gas", "燃气费"),
                            ("property_fee", "物业费"),
                            ("internet", "网络费"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="账单类型",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="账单编号"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="账单标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="账单描述"),
                ),
                ("billing_period_start", models.DateField(verbose_name="计费周期开始")),
                ("billing_period_end", models.DateField(verbose_name="计费周期结束")),
                ("due_date", models.DateField(verbose_name="到期日期")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="总金额(元)"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="已支付金额(元)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("partially_paid", "部分支付"),
                            ("paid", "已支付"),
                            ("overdue", "已逾期"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="账单状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="contracts.rentalcontract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单管理",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="BillSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("equal", "平均分摊"),
                            ("proportion", "按比例分摊"),
                            ("custom", "自定义分摊"),
                        ],
                        max_length=20,
                        verbose_name="分摊方式",
                    ),
                ),
                (
                    "proportion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="分摊比例(%)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="分摊金额(元)"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="是否已支付"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="billing.bill",
                        verbose_name="账单",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_splits",
                        to="contracts.tenant",
                        verbose_name="房客",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单分摊",
                "verbose_name_plural": "账单分摊管理",
                "ordering": ["created_at"],
                "unique_together": {("bill", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "现金"),
                            ("alipay", "支付宝"),
                            ("wechat", "微信支付"),
                            ("bank_transfer", "银行转账"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="支付金额(元)"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="交易单号"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="支付日期")),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="收据编号"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.bill",
                        verbose_name="账单",
                    ),
                ),
                (
                    "bill_split",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.billsplit",
                        verbose_name="账单分摊",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="contracts.tenant",
                        verbose_name="房客",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录管理",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="项", max_length=20, verbose_name="单位"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价(元)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="金额(元)"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.bill",
                        verbose_name="账单",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单明细",
                "verbose_name_plural": "账单明细管理",
                "ordering": ["created_at"],
            },
        ),
    ]
