# Generated by Django 4.2.7 on 2026-05-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV Show")], max_length=10
                    ),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Media",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="TasteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("favorite_genres", models.JSONField(blank=True, default=list)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_ratings", models.IntegerField(default=0)),
                ("rating_deviation_from_imdb", models.FloatField(default=0.0)),
                ("rating_deviation_from_tmdb", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ViewingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("watch_date", models.DateTimeField()),
                ("progress", models.FloatField(default=0.0)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_history",
                        to="movies.media",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Viewing History",
                "ordering": ["-watch_date"],
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("rating", models.FloatField()),
                ("rating_date", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="movies.media",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating_date"],
                "unique_together": {("media", "user_id")},
            },
        ),
    ]
