use crate::types::{Alert, AlertSeverity};
use lettre::{
    transport::smtp::authentication::Credentials,
    Message, SmtpTransport, Transport,
};
use std::sync::Arc;

pub struct EmailChannel {
    pub from_address: String,
    pub from_name: String,
    pub recipients: Vec<String>,
    pub smtp_transport: Option<Arc<SmtpTransport>>,
}

impl EmailChannel {
    pub fn new(
        from_address: String,
        from_name: String,
        recipients: Vec<String>,
        smtp_server: String,
        smtp_port: u16,
        username: String,
        password: String,
    ) -> anyhow::Result<Self> {
        let creds = Credentials::new(username, password);

        let transport = SmtpTransport::builder((smtp_server.as_str(), smtp_port))
            .credentials(creds)
            .build();

        Ok(EmailChannel {
            from_address,
            from_name,
            recipients,
            smtp_transport: Some(Arc::new(transport)),
        })
    }

    pub fn new_default() -> Self {
        EmailChannel {
            from_address: "alerts@localhost".to_string(),
            from_name: "Log Analysis Center".to_string(),
            recipients: vec![],
            smtp_transport: None,
        }
    }

    fn severity_to_color(severity: &AlertSeverity) -> &'static str {
        match severity {
            AlertSeverity::Low => "#3498db",
            AlertSeverity::Medium => "#f39c12",
            AlertSeverity::High => "#e74c3c",
            AlertSeverity::Critical => "#8e44ad",
        }
    }

    fn build_email_body(alert: &Alert) -> String {
        let color = Self::severity_to_color(&alert.severity);
        
        format!(
            r#"
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .header {{ background-color: {}; color: white; padding: 20px; border-radius: 5px 5px 0 0; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .content {{ padding: 20px; background-color: #f9f9f9; border-radius: 0 0 5px 5px; }}
        .section {{ margin-bottom: 20px; }}
        .section h2 {{ font-size: 18px; color: #555; border-bottom: 1px solid #ddd; padding-bottom: 10px; }}
        .details {{ background-color: white; padding: 15px; border-radius: 5px; border: 1px solid #ddd; }}
        .detail-row {{ margin-bottom: 10px; }}
        .detail-label {{ font-weight: bold; color: #777; }}
        .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 Alert: {}</h1>
    </div>
    <div class="content">
        <div class="section">
            <h2>Alert Details</h2>
            <div class="details">
                <div class="detail-row">
                    <span class="detail-label">Severity:</span> {}
                </div>
                <div class="detail-row">
                    <span class="detail-label">Status:</span> {}
                </div>
                <div class="detail-row">
                    <span class="detail-label">Created At:</span> {}
                </div>
                <div class="detail-row">
                    <span class="detail-label">Rule:</span> {}
                </div>
            </div>
        </div>
        <div class="section">
            <h2>Message</h2>
            <div class="details">
                <p>{}</p>
            </div>
        </div>
        <div class="section">
            <h2>Tags</h2>
            <div class="details">
                <p>{}</p>
            </div>
        </div>
        <div class="footer">
            <p>This alert was automatically generated by the Log Analysis & Monitoring Center.</p>
            <p>Please do not reply to this email.</p>
        </div>
    </div>
</body>
</html>
            "#,
            color,
            alert.title,
            alert.severity,
            alert.status,
            alert.created_at.to_rfc3339(),
            alert.rule_name.clone().unwrap_or_else(|| "N/A".to_string()),
            alert.message,
            if alert.tags.is_empty() {
                "No tags".to_string()
            } else {
                alert.tags.join(", ")
            }
        )
    }
}

#[async_trait::async_trait]
impl super::AlertChannel for EmailChannel {
    async fn send(&self, alert: &Alert) -> anyhow::Result<()> {
        if self.recipients.is_empty() {
            tracing::warn!("No email recipients configured, skipping email alert");
            return Ok(());
        }

        if self.smtp_transport.is_none() {
            tracing::warn!("Email channel not configured, skipping email alert");
            return Ok(());
        }

        let transport = self.smtp_transport.as_ref().unwrap();
        
        let body = Self::build_email_body(alert);

        for recipient in &self.recipients {
            let email = Message::builder()
                .from(format!("{} <{}>", self.from_name, self.from_address).parse()?)
                .to(recipient.parse()?)
                .subject(format!("[{}] {}", alert.severity, alert.title))
                .multipart(lettre::message::MultiPart::alternative().singlepart(
                    lettre::message::SinglePart::builder()
                        .header(lettre::message::header::ContentType::TEXT_HTML)
                        .body(body.clone()),
                ))?;

            match transport.clone().send(&email) {
                Ok(_) => {
                    tracing::info!("Email alert sent to {}", recipient);
                }
                Err(e) => {
                    tracing::error!("Failed to send email alert to {}: {}", recipient, e);
                }
            }
        }

        Ok(())
    }

    fn name(&self) -> &str {
        "Email"
    }
}
