version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ../backend:/app
      - ../data:/data
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/dist:/app/dist
    ports:
      - "8080:8080"
    depends_on:
      - backend
