const IMAGENET_LABELS = [
    'tench, Tinca tinca',
    'goldfish, Carassius auratus',
    'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
    'tiger shark, Galeocerdo cuvieri',
    'hammerhead, hammerhead shark',
    'electric ray, crampfish, numbfish, torpedo',
    'stingray',
    'cock',
    'hen',
    'ostrich, Struthio camelus',
    'brambling, Fringilla montifringilla',
    'goldfinch, Carduelis carduelis',
    'house finch, linnet, Carpodacus mexicanus',
    'junco, snowbird',
    'indigo bunting, indigo finch, indigo bird, Passerina cyanea',
    'robin, American robin, Turdus migratorius',
    'bulbul',
    'jay',
    'magpie',
    'chickadee',
    'water ouzel, dipper',
    'kite',
    'bald eagle, American eagle, Haliaeetus leucocephalus',
    'vulture',
    'great grey owl, great gray owl, Strix nebulosa',
    'European fire salamander, Salamandra salamandra',
    'common newt, Triturus vulgaris',
    'eft',
    'spotted salamander, Ambystoma maculatum',
    'axolotl, mud puppy, Ambystoma mexicanum',
    'bullfrog, Rana catesbeiana',
    'tree frog, tree-frog',
    'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui',
    'loggerhead, loggerhead turtle, Caretta caretta',
    'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea',
    'mud turtle',
    'terrapin',
    'box turtle, box tortoise',
    'banded gecko',
    'common iguana, iguana, Iguana iguana',
    'American chameleon, anole, Anolis carolinensis',
    'whiptail, whiptail lizard',
    'agama',
    'frilled lizard, Chlamydosaurus kingi',
    'alligator lizard',
    'Gila monster, Heloderma suspectum',
    'green lizard, Lacerta viridis',
    'African chameleon, Chamaeleo chamaeleon',
    'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis',
    'African crocodile, Nile crocodile, Crocodylus niloticus',
    'American alligator, Alligator mississipiensis',
    'triceratops',
    'thunder snake, worm snake, Carphophis amoenus',
    'ringneck snake, ring-necked snake, Diadophis punctatus',
    'hognose snake, puff adder, sand viper',
    'green snake, grass snake',
    'king snake, kingsnake',
    'garter snake, grass snake',
    'water snake',
    'vine snake',
    'night snake, Hypsiglena torquata',
    'boa constrictor, Constrictor constrictor',
    'rock python, rock snake, Python sebae',
    'Indian cobra, Naja naja',
    'green mamba',
    'sea snake',
    'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus',
    'diamondback, diamondback rattlesnake, Crotalus adamanteus',
    'sidewinder, horned rattlesnake, Crotalus cerastes',
    'trilobite',
    'harvestman, daddy longlegs, Phalangium opilio',
    'scorpion',
    'black and gold garden spider, Argiope aurantia',
    'barn spider, Araneus cavaticus',
    'garden spider, Aranea diademata',
    'black widow, Latrodectus mactans',
    'tarantula',
    'wolf spider, hunting spider',
    'tick',
    'centipede',
    'black grouse',
    'ptarmigan',
    'ruffed grouse, partridge, Bonasa umbellus',
    'prairie chicken, prairie grouse, prairie fowl',
    'peacock',
    'quail',
    'partridge',
    'African grey, African gray, Psittacus erithacus',
    'macaw',
    'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',
    'lorikeet',
    'coucal',
    'bee eater',
    'hornbill',
    'hummingbird',
    'jacamar',
    'toucan',
    'drake',
    'red-breasted merganser, Mergus serrator',
    'goose',
    'black swan, Cygnus atratus',
    'tusker',
    'echidna, spiny anteater, anteater',
    'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus',
    'wallaby, brush kangaroo',
    'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus',
    'wombat',
    'jellyfish',
    'sea anemone, anemone',
    'brain coral',
    'flatworm, platyhelminth',
    'nematode, nematode worm, roundworm',
    'conch',
    'snail',
    'slug',
    'sea slug, nudibranch',
    'chiton, coat-of-mail shell, sea cradle, polyplacophore',
    'chambered nautilus, pearly nautilus, nautilus',
    'Dungeness crab, Cancer magister',
    'rock crab, Cancer irroratus',
    'fiddler crab',
    'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica',
    'American lobster, Northern lobster, Maine lobster, Homarus americanus',
    'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish',
    'crayfish, crawfish, crawdad, crawdaddy',
    'hermit crab',
    'isopod',
    'white stork, Ciconia ciconia',
    'black stork, Ciconia nigra',
    'spoonbill',
    'flamingo',
    'little blue heron, Egretta caerulea',
    'American egret, great white heron, Egretta albus',
    'bittern',
    'crane',
    'limpkin, Aramus pictus',
    'European gallinule, Porphyrio porphyrio',
    'American coot, marsh hen, mud hen, water hen, Fulica americana',
    'bustard',
    'ruddy turnstone, Arenaria interpres',
    'red-backed sandpiper, dunlin, Erolia alpina',
    'redshank, Tringa totanus',
    'dowitcher',
    'oystercatcher, oyster catcher',
    'pelican',
    'king penguin, Aptenodytes patagonica',
    'albatross, mollymawk',
    'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus',
    'killer whale, killer, orca, grampus, sea wolf, Orcinus orca',
    'dugong, Dugong dugon',
    'sea lion',
    'Chihuahua',
    'Japanese spaniel',
    'Maltese dog, Maltese terrier, Maltese',
    'Pekinese, Pekingese, Peke',
    'Shih-Tzu',
    'Blenheim spaniel',
    'papillon',
    'toy terrier',
    'Rhodesian ridgeback',
    'Afghan hound, Afghan',
    'basset, basset hound',
    'beagle',
    'bloodhound, sleuthhound',
    'bluetick',
    'black-and-tan coonhound',
    'Walker hound, Walker foxhound',
    'English foxhound',
    'redbone',
    'borzoi, Russian wolfhound',
    'Irish wolfhound',
    'Italian greyhound',
    'whippet',
    'Ibizan hound, Ibizan Podenco',
    'Norwegian elkhound, elkhound',
    'otterhound, otter hound',
    'Saluki, gazelle hound',
    'Scottish deerhound, deerhound',
    'Weimaraner',
    'Staffordshire bullterrier, Staffordshire bull terrier',
    'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',
    'Bedlington terrier',
    'Border terrier',
    'Kerry blue terrier',
    'Irish terrier',
    'Norfolk terrier',
    'Norwich terrier',
    'Yorkshire terrier',
    'wire-haired fox terrier',
    'Lakeland terrier',
    'Sealyham terrier, Sealyham',
    'Airedale, Airedale terrier',
    'cairn, cairn terrier',
    'Australian terrier',
    'Dandie Dinmont, Dandie Dinmont terrier',
    'Boston bull, Boston terrier',
    'miniature schnauzer',
    'giant schnauzer',
    'standard schnauzer',
    'Scotch terrier, Scottish terrier, Scottie',
    'Tibetan terrier, chrysanthemum dog',
    'silky terrier, Sydney silky',
    'soft-coated wheaten terrier',
    'West Highland white terrier',
    'Lhasa, Lhasa apso',
    'flat-coated retriever',
    'curly-coated retriever',
    'golden retriever',
    'Labrador retriever',
    'Chesapeake Bay retriever',
    'German short-haired pointer',
    'vizsla, Hungarian pointer',
    'English setter',
    'Irish setter, red setter',
    'Gordon setter',
    'Brittany spaniel',
    'clumber, clumber spaniel',
    'English springer, English springer spaniel',
    'Welsh springer spaniel',
    'cocker spaniel, English cocker spaniel, cocker',
    'Sussex spaniel',
    'Irish water spaniel',
    'kuvasz',
    'schipperke',
    'groenendael dog',
    'malinois',
    'briard',
    'kelpie',
    'komondor',
    'Old English sheepdog, bobtail',
    'Shetland sheepdog, Shetland sheep dog, Shetland',
    'collie',
    'Border collie',
    'Bouvier des Flandres, Bouviers des Flandres',
    'Rottweiler',
    'German shepherd, German shepherd dog, German police dog, alsatian',
    'Doberman, Doberman pinscher',
    'miniature pinscher',
    'Greater Swiss Mountain dog',
    'Bernese mountain dog',
    'Appenzeller',
    'EntleBucher',
    'boxer',
    'bull mastiff',
    'Tibetan mastiff',
    'French bulldog',
    'Great Dane',
    'Saint Bernard, St Bernard',
    'Eskimo dog, husky',
    'malamute, malemute, Alaskan malamute',
    'Siberian husky',
    'dalmatian, coach dog, carriage dog',
    'affenpinscher, monkey pinscher, monkey dog',
    'basenji',
    'pug, pug-dog',
    'Leonberg',
    'Newfoundland, Newfoundland dog',
    'Great Pyrenees',
    'Samoyed, Samoyede',
    'Pomeranian',
    'chow, chow chow',
    'keeshond',
    'Brabancon griffon',
    'Pembroke, Pembroke Welsh corgi',
    'Cardigan, Cardigan Welsh corgi',
    'toy poodle',
    'miniature poodle',
    'standard poodle',
    'Mexican hairless',
    'timber wolf, grey wolf, gray wolf, Canis lupus',
    'white wolf, Arctic wolf, Canis lupus tundrarum',
    'red wolf, maned wolf, Canis rufus, Canis niger',
    'coyote, prairie wolf, brush wolf, Canis latrans',
    'dingo, warrigal, warragal, Canis dingo',
    'dhole, Cuon alpinus',
    'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus',
    'hyena, hyaena',
    'red fox, Vulpes vulpes',
    'kit fox, Vulpes macrotis',
    'Arctic fox, white fox, Alopex lagopus',
    'grey fox, gray fox, Urocyon cinereoargenteus',
    'tabby, tabby cat',
    'tiger cat',
    'Persian cat',
    'Siamese cat, Siamese',
    'Egyptian cat',
    'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor',
    'lynx, catamount',
    'leopard, Panthera pardus',
    'snow leopard, ounce, Panthera uncia',
    'jaguar, panther, Panthera onca',
    'lion, king of beasts, Panthera leo',
    'tiger, Panthera tigris',
    'cheetah, chetah, Acinonyx jubatus',
    'brown bear, bruin, Ursus arctos',
    'American black bear, black bear, Ursus americanus',
    'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus',
    'sloth bear, Melursus ursinus, Ursus ursinus',
    'mongoose',
    'meerkat, mierkat',
    'tiger beetle',
    'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle',
    'ground beetle, carabid beetle',
    'long-horned beetle, longicorn, longicorn beetle',
    'leaf beetle, chrysomelid',
    'dung beetle',
    'rhinoceros beetle',
    'weevil',
    'fly',
    'bee',
    'ant, emmet, pismire',
    'grasshopper, hopper',
    'cricket',
    'walking stick, walkingstick, stick insect',
    'cockroach, roach',
    'mantis, mantid',
    'cicada, cicala',
    'leafhopper',
    'lacewing, lacewing fly',
    'dragonfly, darning needle, devil\'s darning needle, skeeter hawk, mosquito hawk, snake doctor, snake feeder, sewing needle, darner, devil\'s arrow, devil\'s darning needle',
    'damselfly',
    'admiral',
    'ringlet, ringlet butterfly',
    'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus',
    'cabbage butterfly',
    'sulphur butterfly, sulfur butterfly',
    'lycaenid, lycaenid butterfly',
    'starfish, sea star',
    'sea urchin',
    'sea cucumber, holothurian',
    'wood rabbit, cottontail, cottontail rabbit',
    'hare',
    'Angora, Angora rabbit',
    'hamster',
    'porcupine, hedgehog',
    'fox squirrel, eastern fox squirrel, Sciurus niger',
    'marmot',
    'beaver',
    'guinea pig, Cavia cobaya',
    'sorrel',
    'zebra',
    'hog, pig, grunter, squealer, Sus scrofa',
    'wild boar, boar, Sus scrofa',
    'warthog',
    'hippopotamus, hippo, river horse, Hippopotamus amphibius',
    'ox',
    'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis',
    'bison',
    'ram, tup',
    'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis',
    'ibex, Capra ibex',
    'hartebeest',
    'impala, Aepyceros melampus',
    'gazelle',
    'Arabian camel, dromedary, Camelus dromedarius',
    'llama',
    'weasel',
    'mink',
    'polecat, fitch, foulmart, foumart, Mustela putorius',
    'black-footed ferret, ferret, Mustela nigripes',
    'otter',
    'skunk, polecat, wood pussy',
    'badger',
    'armadillo',
    'three-toed sloth, ai, Bradypus tridactylus',
    'orangutan, orang, orangutang, Pongo pygmaeus',
    'gorilla, Gorilla gorilla',
    'chimpanzee, chimp, Pan troglodytes',
    'gibbon, Hylobates lar',
    'siamang, Hylobates syndactylus, Symphalangus syndactylus',
    'guenon, guenon monkey',
    'patas, hussar monkey, Erythrocebus patas',
    'baboon',
    'macaque',
    'langur',
    'colobus, colobus monkey',
    'proboscis monkey, Nasalis larvatus',
    'marmoset',
    'capuchin, ringtail, Cebus capucinus',
    'howler monkey, howler',
    'titi, titi monkey',
    'spider monkey, Ateles geoffroyi',
    'squirrel monkey, Saimiri sciureus',
    'Madagascar cat, ring-tailed lemur, Lemur catta',
    'indri, indris, Indri indri, Indri brevicaudatus',
    'Indian elephant, Elephas maximus',
    'African elephant, Loxodonta africana',
    'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens',
    'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca',
    'barracouta, snoek',
    'eel',
    'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch',
    'rock beauty, Holocanthus tricolor',
    'anemone fish',
    'sturgeon',
    'gar, garfish, garpike, billfish, Lepisosteus osseus',
    'lionfish',
    'puffer, pufferfish, blowfish, globefish',
    'abacus',
    'abaya',
    'academic gown, academic robe, judge\'s robe',
    'accordion, piano accordion, squeeze box',
    'acoustic guitar',
    'aircraft carrier, carrier, flattop, attack aircraft carrier',
    'airliner',
    'airship, dirigible',
    'altar',
    'ambulance',
    'amphibian, amphibious vehicle',
    'analog clock',
    'apiary, bee house',
    'apron',
    'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin',
    'assault rifle, assault gun',
    'backpack, back pack, knapsack, packsack, rucksack, haversack',
    'bakery, bakeshop, bakehouse',
    'balance beam, beam',
    'balloon',
    'ballpoint, ballpoint pen, ballpen, Biro',
    'Band Aid',
    'banjo',
    'bannister, banister, balustrade, balusters, handrail',
    'barbell',
    'barber chair',
    'barbershop',
    'barn',
    'barometer',
    'barrel, cask',
    'barrow, garden cart, lawn cart, wheelbarrow',
    'baseball',
    'basketball',
    'bassinet',
    'bassoon',
    'bathing cap, swimming cap',
    'bath towel',
    'bathtub, bathing tub, bath, tub',
    'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon',
    'beacon, lighthouse, beacon light, pharos',
    'beaker',
    'bearskin, busby, shako',
    'beer bottle',
    'beer glass',
    'bell cote, bell cot',
    'bib',
    'bicycle-built-for-two, tandem bicycle, tandem',
    'bikini, two-piece',
    'binder, ring-binder',
    'binoculars, field glasses, opera glasses',
    'birdhouse',
    'boathouse',
    'bobsled, bobsleigh, bob',
    'bolo tie, bolo, bola tie, bola',
    'bonnet, poke bonnet',
    'bookcase',
    'bookshop, bookstore, bookstall',
    'bottlecap',
    'bow',
    'bow tie, bow-tie, bowtie',
    'brass, memorial tablet, plaque',
    'brassiere, bra, bandeau',
    'breakwater, groin, groyne, mole, bulwark, seawall, jetty',
    'breastplate, aegis, egis',
    'broom',
    'bucket, pail',
    'buckle',
    'bulletproof vest',
    'bullet train, bullet',
    'butcher shop, meat market',
    'cab, hack, taxi, taxicab',
    'caldron, cauldron',
    'candle, taper, wax light',
    'cannon',
    'canoe',
    'can opener, tin opener',
    'cardigan',
    'car mirror',
    'carousel, carrousel, merry-go-round, roundabout, whirligig',
    'carpenter\'s kit, tool kit',
    'carton',
    'car wheel',
    'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM',
    'cassette',
    'cassette player',
    'castle',
    'catamaran',
    'CD player',
    'cello, violoncello',
    'cellular telephone, cellular phone, cellphone, cell, mobile phone',
    'chain',
    'chainlink fence',
    'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour',
    'chain saw, chainsaw',
    'chest',
    'chiffonier, commode',
    'chime, bell, gong',
    'china cabinet, china closet',
    'Christmas stocking',
    'church, church building',
    'cinema, movie theater, movie theatre, movie house, picture palace',
    'cleaver, meat cleaver, chopper',
    'cliff dwelling',
    'cloak',
    'clog, geta, patten, sabot',
    'cocktail shaker',
    'coffee mug',
    'coffeepot',
    'coil, spiral, volute, whorl, helix',
    'combination lock',
    'computer keyboard, keypad',
    'confectionery, confectionary, candy store',
    'container ship, containership, container vessel',
    'convertible',
    'corkscrew, bottle screw',
    'cornet, horn, trumpet, trump',
    'cowboy boot',
    'cowboy hat, ten-gallon hat',
    'cradle',
    'crane',
    'crash helmet',
    'crate',
    'crib, cot',
    'Crock Pot',
    'croquet ball',
    'crutch',
    'cuirass',
    'dam, dike, dyke',
    'desk',
    'desktop computer',
    'dial telephone, dial phone',
    'diaper, nappy, napkin',
    'digital clock',
    'digital watch',
    'dining table, board',
    'dishrag, dishcloth',
    'dishwasher, dish washer, dishwashing machine',
    'disk brake, disc brake',
    'dock, dockage, docking facility',
    'dogsled, dog sled, dog sleigh',
    'dome',
    'doormat, welcome mat',
    'drilling platform, offshore rig',
    'drum, membranophone, tympan',
    'drumstick',
    'dumbbell',
    'Dutch oven',
    'electric fan, blower',
    'electric guitar',
    'electric locomotive',
    'entertainment center',
    'envelope',
    'espresso maker',
    'face powder',
    'feather boa, boa',
    'file, file cabinet, filing cabinet',
    'fireboat',
    'fire engine, fire truck',
    'fire screen, fireguard',
    'flagpole, flagstaff',
    'flute, transverse flute',
    'folding chair',
    'football helmet',
    'forklift',
    'fountain',
    'fountain pen',
    'four-poster',
    'freight car',
    'French horn, horn',
    'frying pan, frypan, skillet',
    'fur coat',
    'garbage truck, dustcart',
    'gasmask, respirator, gas helmet',
    'gas pump, gasoline pump, petrol pump, island dispenser',
    'goblet',
    'go-kart',
    'golf ball',
    'golfcart, golf cart',
    'gondola',
    'gong, tam-tam',
    'gown',
    'grand piano, grand',
    'greenhouse, nursery, glasshouse',
    'grille, radiator grille',
    'grocery store, grocery, food market, market',
    'guillotine',
    'hair slide',
    'hair spray',
    'half track',
    'hammer',
    'hamper',
    'hand blower, blow dryer, blow drier, hair dryer, hair drier',
    'hand-held computer, hand-held microcomputer',
    'handkerchief, hankie, hanky, hankey',
    'hard disc, hard disk, fixed disk',
    'harmonica, mouth organ, harp, mouth harp',
    'harp',
    'harvester, reaper',
    'hatchet',
    'holster',
    'home theater, home theatre',
    'honeycomb',
    'hook, claw',
    'hoopskirt, crinoline',
    'horizontal bar, high bar',
    'horse cart, horse-cart',
    'hourglass',
    'iPod',
    'iron, smoothing iron',
    'jack-o\'-lantern',
    'jean, blue jean, denim',
    'jeep, landrover',
    'jersey, T-shirt, tee shirt',
    'jigsaw puzzle',
    'jinrikisha, ricksha, rickshaw',
    'joystick',
    'kimono',
    'knee pad',
    'knot',
    'lab coat, laboratory coat',
    'ladle',
    'lampshade, lamp shade',
    'laptop, laptop computer',
    'lawn mower, mower',
    'lens cap, lens cover',
    'letter opener, paper knife, paperknife',
    'library',
    'lifeboat',
    'lighter, light, igniter, ignitor',
    'limousine, limo',
    'liner, ocean liner',
    'lipstick, lip rouge',
    'Loafer',
    'lotion',
    'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system',
    'loupe, jeweler\'s loupe',
    'lumbermill, sawmill',
    'magnetic compass',
    'mailbag, postbag',
    'mailbox, letter box',
    'maillot',
    'maillot, tank suit',
    'manhole cover',
    'maraca',
    'marimba, xylophone',
    'mask',
    'matchstick',
    'maypole',
    'maze, labyrinth',
    'measuring cup',
    'medicine chest, medicine cabinet',
    'megalith, megalithic structure',
    'microphone, mike',
    'microwave, microwave oven',
    'military uniform',
    'milk can',
    'minibus',
    'miniskirt, mini',
    'minivan',
    'missile',
    'mitten',
    'mixing bowl',
    'mobile home, manufactured home',
    'Model T',
    'modem',
    'monastery',
    'monitor',
    'moped',
    'mortar',
    'mortarboard',
    'mosque',
    'mosquito net',
    'motor scooter, scooter',
    'mountain bike, all-terrain bike, off-roader',
    'mountain tent',
    'mouse, computer mouse',
    'mousetrap',
    'moving van',
    'muzzle',
    'nail',
    'neck brace',
    'necklace',
    'nipple',
    'notebook, notebook computer',
    'obelisk',
    'oboe, hautboy, hautbois',
    'ocarina, sweet potato',
    'odometer, hodometer, mileometer, milometer',
    'oil filter',
    'organ, pipe organ',
    'oscilloscope, scope, cathode-ray oscilloscope, CRO',
    'overskirt',
    'oxcart',
    'oxygen mask',
    'packet',
    'paddle, boat paddle',
    'paddlewheel, paddle wheel',
    'padlock',
    'paintbrush',
    'pajama, pyjama, pj\'s, jammies',
    'palace',
    'panpipe, pandean pipe, syrinx',
    'paper towel',
    'parachute, chute',
    'parallel bars, bars',
    'park bench',
    'parking meter',
    'passenger car, coach, carriage',
    'patio, terrace',
    'pay-phone, pay-station',
    'pedestal, plinth, footstall',
    'pencil box, pencil case',
    'pencil sharpener',
    'perfume, essence',
    'Petri dish',
    'photocopier',
    'pick, plectrum, plectron',
    'pickelhaube',
    'picket fence, paling',
    'pickup, pickup truck',
    'pier',
    'piggy bank, penny bank',
    'pill bottle',
    'pillow',
    'ping-pong ball',
    'pinwheel',
    'pirate, pirate ship',
    'pitcher, ewer',
    'plane, carpenter\'s plane, woodworking plane',
    'planetarium',
    'plastic bag',
    'plate rack',
    'plow, plough',
    'plunger, plumber\'s helper',
    'Polaroid camera, Polaroid Land camera',
    'pole',
    'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria',
    'poncho',
    'pool table, billiard table, snooker table',
    'pop bottle, soda bottle',
    'pot, flowerpot',
    'potter\'s wheel',
    'power drill',
    'prayer rug, prayer mat',
    'printer',
    'prison, prison house',
    'projectile, missile',
    'projector',
    'puck, hockey puck',
    'punching bag, punch bag, punching ball, punchball',
    'purse',
    'quill, quill pen',
    'quilt, comforter, comfort, puff',
    'racer, race car, racing car',
    'racket, racquet',
    'radiator',
    'radio, wireless',
    'radio telescope, radio reflector',
    'rain barrel',
    'recreational vehicle, RV, R.V.',
    'reel',
    'reflex camera',
    'refrigerator, icebox',
    'remote control, remote',
    'restaurant, eating house, eating place, eatery',
    'revolver, six-gun, six-shooter',
    'rifle',
    'rocking chair, rocker',
    'rotisserie',
    'rubber eraser, rubber, pencil eraser',
    'rugby ball',
    'rule, ruler',
    'running shoe',
    'safe',
    'safety pin',
    'saltshaker, salt shaker',
    'sandal',
    'sarong',
    'sax, saxophone',
    'scabbard',
    'scale, weighing machine',
    'school bus',
    'schooner',
    'scoreboard',
    'screen, CRT screen',
    'screw',
    'screwdriver',
    'seat belt, seatbelt',
    'sewing machine',
    'shield, buckler',
    'shoe shop, shoe-shop, shoe store',
    'shoji',
    'shopping basket',
    'shopping cart',
    'shovel',
    'shower cap',
    'shower curtain',
    'ski',
    'ski mask',
    'sleeping bag',
    'slide rule, slipstick',
    'sliding door',
    'slot, one-armed bandit',
    'snorkel',
    'snowmobile',
    'snowplow, snowplough',
    'soap dispenser',
    'soccer ball',
    'sock',
    'solar dish, solar collector, solar furnace',
    'sombrero',
    'soup bowl',
    'space bar',
    'space heater',
    'space shuttle',
    'spatula',
    'speedboat',
    'spider web, spider\'s web',
    'spindle',
    'sports car, sport car',
    'spotlight, spot',
    'stage',
    'steam locomotive',
    'steel arch bridge',
    'steel drum',
    'stethoscope',
    'stole',
    'stone wall',
    'stopwatch, stop watch',
    'stove',
    'strainer',
    'streetcar, tram, tramcar, trolley, trolley car',
    'stretcher',
    'studio couch, day bed',
    'stupa, tope',
    'submarine, pigboat, sub, U-boat',
    'suit, suit of clothes',
    'sundial',
    'sunglass',
    'sunglasses, dark glasses, shades',
    'sunscreen, sunblock, sun blocker',
    'suspension bridge',
    'swab, swob, mop',
    'sweatshirt',
    'swimming trunks, bathing trunks',
    'swing',
    'switch, electric switch, electrical switch',
    'syringe',
    'table lamp',
    'tank, army tank, armored combat vehicle, armoured combat vehicle',
    'tape player',
    'teapot',
    'teddy, teddy bear',
    'television, television system',
    'tennis ball',
    'thatch, thatched roof',
    'theater curtain, theatre curtain',
    'thimble',
    'thresher, thrasher, threshing machine',
    'throne',
    'tile roof',
    'toaster',
    'tobacco shop, tobacconist shop, tobacconist',
    'toilet seat',
    'torch',
    'totem pole',
    'tow truck, tow car, wrecker',
    'toyshop',
    'tractor',
    'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi',
    'tray',
    'trench coat',
    'tricycle, trike, velocipede',
    'trimaran',
    'tripod',
    'triumphal arch',
    'trolleybus, trolley coach, trackless trolley',
    'trombone',
    'tub, vat',
    'turnstile',
    'typewriter keyboard',
    'umbrella',
    'unicycle, monocycle',
    'upright, upright piano',
    'vacuum, vacuum cleaner',
    'vase',
    'vault',
    'velvet',
    'vending machine',
    'vestment',
    'viaduct',
    'violin, fiddle',
    'volleyball',
    'waffle iron',
    'wall clock',
    'wallet, billfold, notecase, pocketbook',
    'wardrobe, closet, press',
    'warplane, military plane',
    'washbasin, handbasin, washbowl, lavabo, wash-hand basin',
    'washer, automatic washer, washing machine',
    'water bottle',
    'water jug',
    'water tower',
    'whiskey jug',
    'whistle',
    'wig',
    'window screen',
    'window shade',
    'Windsor tie',
    'wine bottle',
    'wing',
    'wok',
    'wooden spoon',
    'wool, woolen, woollen',
    'worm fence, snake fence, snake-rail fence, Virginia fence',
    'wreck',
    'yawl',
    'yurt',
    'web site, website, internet site, site',
    'comic book',
    'crossword puzzle, crossword',
    'street sign',
    'traffic light, traffic signal, stoplight',
    'book jacket, dust cover, dust jacket, dust wrapper',
    'menu',
    'plate',
    'guacamole',
    'consomme',
    'hot pot, hotpot',
    'trifle',
    'ice cream, icecream',
    'ice lolly, lolly, lollipop, popsicle',
    'French loaf',
    'bagel, beigel',
    'pretzel',
    'cheeseburger',
    'hotdog, hot dog, red hot',
    'mashed potato',
    'head cabbage',
    'broccoli',
    'cauliflower',
    'zucchini, courgette',
    'spaghetti squash',
    'acorn squash',
    'butternut squash',
    'cucumber, cuke',
    'artichoke, globe artichoke',
    'bell pepper',
    'cardoon',
    'mushroom',
    'Granny Smith',
    'strawberry',
    'orange',
    'lemon',
    'fig',
    'pineapple, ananas',
    'banana',
    'jackfruit, jak, jack',
    'custard apple',
    'pomegranate',
    'hay',
    'carbonara',
    'chocolate sauce, chocolate syrup',
    'dough',
    'meat loaf, meatloaf',
    'pizza, pizza pie',
    'potpie',
    'burrito',
    'red wine',
    'espresso',
    'cup',
    'eggnog',
    'alp',
    'bubble',
    'cliff, drop, drop-off',
    'coral reef',
    'geyser',
    'lakeside, lakeshore',
    'promontory, headland, head, foreland',
    'sandbar, sand bar',
    'seashore, coast, seacoast, sea-coast',
    'valley, vale',
    'volcano',
    'ballplayer, baseball player',
    'groom, bridegroom',
    'scuba diver',
    'rapeseed',
    'daisy',
    'yellow lady\'s slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum',
    'corn',
    'acorn',
    'hip, rose hip, rosehip',
    'buckeye, horse chestnut, conker',
    'coral fungus',
    'agaric',
    'gyromitra',
    'stinkhorn, carrion fungus',
    'earthstar',
    'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa',
    'bolete',
    'ear, spike, capitulum',
    'toilet tissue, toilet paper, bathroom tissue'
];

const CATEGORY_HIERARCHY = {
    '哺乳动物': [
        '狗', '犬', '猫', '猫科动物', '马', '牛', '羊', '猪', '兔子', '仓鼠',
        '熊', '大象', '长颈鹿', '犀牛', '河马', '斑马',
        '狮子', '老虎', '豹子', '美洲豹', '猎豹',
        '狼', '狐狸', '土狼',
        '猴子', '黑猩猩', '大猩猩', '猩猩',
        '袋鼠', '考拉', '树懒',
        '鲸', '海豚', '海狮', '海豹',
        '松鼠', '海狸', '土拨鼠', '刺猬',
        '骆驼', '羊驼', '水獭', '黄鼠狼',
        '臭鼬', '獾', '犰狳', '大熊猫', '小熊猫'
    ],
    '宠物': [
        '狗', '猫', '兔子', '仓鼠', '鹦鹉', '金鱼', '海龟', '变色龙',
        '柯基犬', '金毛犬', '泰迪犬', '哈士奇', '布偶猫', '橘猫'
    ],
    '野生猫科': [
        '狮子', '老虎', '豹子', '美洲豹', '猎豹', '雪豹', '美洲狮', '山猫', '猞猁'
    ],
    '大型食草动物': [
        '大象', '长颈鹿', '犀牛', '河马', '斑马', '骆驼', '牦牛', '羚羊'
    ],
    '鱼类': [
        '金鱼', '鲤鱼', '鲨鱼', '鳐鱼', '电鳗', '鲟鱼', '海豚', '河豚',
        '小丑鱼', '狮子鱼'
    ],
    '鸟类': [
        '鹦鹉', '孔雀', '企鹅', '火烈鸟', '猫头鹰', '鹰', '啄木鸟',
        '鸽子', '鸡', '鸭', '鹅', '鸵鸟', '蜂鸟', '麻雀', '喜鹊'
    ],
    '爬行动物': [
        '蜥蜴', '蛇', '龟', '鳄鱼', '变色龙', '壁虎', '科莫多龙'
    ],
    '两栖动物': [
        '青蛙', '蟾蜍', '蝾螈', '娃娃鱼'
    ],
    '昆虫': [
        '蝴蝶', '蜜蜂', '蜘蛛', '蝎子', '瓢虫', '蚂蚁', '蟑螂', '蚱蜢',
        '蜻蜓', '萤火虫', '蚊子', '苍蝇', '甲虫'
    ],
    '海洋生物': [
        '海星', '水母', '珊瑚', '章鱼', '鱿鱼', '虾', '螃蟹', '龙虾',
        '海螺', '蜗牛', '海参'
    ],
    
    '甜点': [
        '冰淇淋', '蛋糕', '奶油蛋糕', '巧克力', '甜甜圈', '布丁',
        '提拉米苏', '马卡龙', '曲奇饼干', '奶油', '棒棒糖', '冰棒',
        '水果蛋糕', '芝士蛋糕'
    ],
    '水果': [
        '苹果', '香蕉', '橙子', '草莓', '蓝莓', '西瓜', '葡萄', '樱桃',
        '芒果', '猕猴桃', '菠萝', '柠檬', '无花果', '石榴', '椰子',
        '哈密瓜', '桃子', '梨', '柚子', '荔枝', '榴莲'
    ],
    '蔬菜': [
        '西兰花', '花椰菜', '黄瓜', '西红柿', '甜椒', '胡萝卜', '土豆',
        '白菜', '生菜', '菠菜', '洋葱', '大蒜', '蘑菇', '玉米',
        '茄子', '西葫芦', '南瓜', '芦笋', '芹菜'
    ],
    '主食': [
        '面包', '法式面包', '贝果', '汉堡', '芝士汉堡', '热狗', '披萨',
        '米饭', '意大利面', '面条', '三明治', '热狗', '墨西哥卷饼',
        '肉丸子', '烤肉', '煎蛋'
    ],
    '饮料': [
        '咖啡', '浓缩咖啡', '红酒', '茶', '奶茶', '可乐', '果汁',
        '啤酒', '蛋酒', '矿泉水'
    ],
    '零食': [
        '薯片', '饼干', '巧克力', '糖果', '坚果', '爆米花', '棉花糖',
        '花生酱', '果冻', '蜜饯'
    ],
    
    '沙发': [
        '沙发', '长沙发', '双人沙发', '沙发床', '贵妃椅'
    ],
    '椅子': [
        '椅子', '扶手椅', '办公椅', '餐椅', '折叠椅', '摇椅',
        '电竞椅', '转椅', '休闲椅'
    ],
    '桌子': [
        '桌子', '书桌', '餐桌', '咖啡桌', '茶几', '床头柜',
        '电脑桌', '梳妆台'
    ],
    '床': [
        '床', '双人床', '单人床', '上下铺', '双层床', '婴儿床',
        '四帷柱床', '榻榻米'
    ],
    '柜子': [
        '衣柜', '书柜', '书架', '橱柜', '五斗柜', '电视柜',
        '酒柜', '鞋柜', '床头柜'
    ],
    '家用电器': [
        '电视', '冰箱', '洗衣机', '空调', '微波炉', '烤箱', '洗碗机',
        '吸尘器', '吹风机', '电风扇', '电熨斗', '烤面包机', '咖啡机',
        '热水器', '空气净化器', '加湿器', '电饭煲', '电磁炉'
    ],
    '厨房用品': [
        '锅', '平底锅', '电饭煲', '炒锅', '蒸锅',
        '碗', '盘子', '杯子', '咖啡杯', '水杯',
        '筷子', '勺子', '叉子', '刀', '砧板',
        '茶壶', '咖啡壶', '酒瓶', '酒杯',
        '菜篮子', '保鲜盒', '保鲜膜'
    ],
    '家居装饰': [
        '台灯', '吊灯', '落地灯', '花瓶', '时钟', '闹钟', '挂画',
        '地毯', '窗帘', '百叶窗', '门帘', '靠垫', '枕头', '被子',
        '毛巾', '浴巾', '镜子', '相框', '蜡烛', '香薰'
    ],
    
    '轿车': [
        '汽车', '轿车', '跑车', '敞篷车', '电动车', 'SUV', '越野车'
    ],
    '商用车': [
        '卡车', '货车', '公交车', '校车', '面包车', '房车', '拖车',
        '工程车', '消防车', '救护车', '警车', '出租车'
    ],
    '两轮车': [
        '摩托车', '自行车', '电动车', '三轮车', '滑板车'
    ],
    '飞机': [
        '客机', '战斗机', '直升机', '无人机', '运输机', '轰炸机',
        '航天飞机'
    ],
    '船舶': [
        '轮船', '邮轮', '货船', '渔船', '游艇', '快艇', '独木舟',
        '帆船', '皮划艇', '潜水艇'
    ],
    '火车': [
        '火车', '高铁', '地铁', '轻轨', '有轨电车', '蒸汽火车'
    ],
    
    '智能手机': [
        '手机', '智能手机', 'iPhone', '安卓手机'
    ],
    '电脑': [
        '电脑', '笔记本电脑', '台式电脑', '平板', 'iPad'
    ],
    '电脑配件': [
        '键盘', '鼠标', '显示器', '音箱', '耳机', '摄像头', 'U盘',
        '硬盘', '光驱', '打印机', '扫描仪', '路由器'
    ],
    '相机': [
        '相机', '单反相机', '微单相机', '拍立得', '摄像机'
    ],
    '音频设备': [
        '耳机', '音箱', '麦克风', '收音机', 'CD播放器', '录音机',
        'MP3播放器', '耳机放大器'
    ],
    '可穿戴设备': [
        '手表', '智能手表', '手环', '智能手环', 'VR眼镜', '耳机'
    ],
    
    '上衣': [
        '衬衫', 'T恤', '毛衣', '运动衫', '外套', '夹克', '风衣',
        '大衣', '羽绒服', '卫衣', 'POLO衫', '背心'
    ],
    '下装': [
        '牛仔裤', '裤子', '休闲裤', '西裤', '裙子', '连衣裙',
        '短裤', '运动裤', '打底裤'
    ],
    '鞋子': [
        '运动鞋', '跑鞋', '篮球鞋', '凉鞋', '拖鞋', '靴子',
        '皮鞋', '高跟鞋', '帆布鞋', '马丁靴', '雪地靴'
    ],
    '配饰': [
        '帽子', '围巾', '领带', '领结', '手套', '手表', '项链',
        '手链', '耳环', '戒指', '腰带', '钱包', '手提包', '背包',
        '眼镜', '太阳镜', '口罩'
    ],
    '内衣': [
        '内衣', '内裤', '胸罩', '睡衣', '家居服', '浴袍'
    ],
    
    '弦乐器': [
        '吉他', '电吉他', '原声吉他', '小提琴', '大提琴', '中提琴',
        '贝斯', '竖琴', '曼陀林', '班卓琴'
    ],
    '键盘乐器': [
        '钢琴', '电子琴', '手风琴', '口琴', '管风琴', '合成器'
    ],
    '打击乐器': [
        '鼓', '架子鼓', '定音鼓', '木琴', '锣', '铃鼓', '沙锤',
        '响板', '钢鼓'
    ],
    '管乐器': [
        '萨克斯管', '长笛', '单簧管', '双簧管', '小号', '长号',
        '圆号', '大号', '口琴', '竖笛'
    ],
    
    '球类运动': [
        '篮球', '足球', '网球', '棒球', '排球', '橄榄球', '高尔夫球',
        '乒乓球', '羽毛球', '棒球', '保龄球', '台球'
    ],
    '健身器材': [
        '杠铃', '哑铃', '跑步机', '动感单车', '椭圆机', '瑜伽垫',
        '健身球', '弹力带', '引体向上杆', '拳击沙袋'
    ],
    '户外运动': [
        '自行车', '滑板', '滑雪板', '滑雪杖', '冲浪板', '风筝',
        '帐篷', '睡袋', '登山杖', '头盔', '护膝', '护肘'
    ],
    
    '办公文具': [
        '书', '笔记本', '文件夹', '铅笔', '钢笔', '圆珠笔', '橡皮',
        '尺子', '订书机', '计算器', '胶带', '剪刀', '便利贴',
        '胶水', '回形针', '书签'
    ],
    '办公设备': [
        '办公桌', '办公椅', '打印机', '复印机', '传真机', '投影仪',
        '碎纸机', '打卡机', '电话机'
    ],
    
    '住宅建筑': [
        '房子', '房屋', '别墅', '公寓', '农舍', '蒙古包', '城堡',
        '宫殿', '摩天大楼'
    ],
    '公共建筑': [
        '教堂', '清真寺', '寺庙', '学校', '医院', '图书馆', '博物馆',
        '体育场', '机场', '火车站'
    ],
    '桥梁': [
        '桥梁', '吊桥', '拱桥', '高架桥', '悬索桥'
    ],
    
    '山峰': [
        '山', '高山', '悬崖', '火山', '雪山'
    ],
    '水域': [
        '湖泊', '河流', '海洋', '海滩', '瀑布', '喷泉', '珊瑚礁',
        '温泉', '池塘'
    ],
    '森林': [
        '森林', '树林', '草原', '沙漠', '洞穴'
    ],
    
    '化妆用品': [
        '口红', '粉底', '睫毛膏', '眼影', '腮红', '指甲油', '香水',
        '护肤品', '洗面奶', '面霜', '防晒霜', '卸妆油'
    ],
    '清洁用品': [
        '扫帚', '拖把', '吸尘器', '垃圾桶', '洗衣粉', '肥皂',
        '洗洁精', '消毒液', '卫生纸', '纸巾', '垃圾袋'
    ],
    '医疗用品': [
        '创可贴', '绷带', '体温计', '血压计', '听诊器', '注射器',
        '口罩', '护目镜', '轮椅', '拐杖', '急救箱'
    ],
    '工具': [
        '锤子', '螺丝刀', '扳手', '钳子', '电钻', '锯子', '斧子',
        '铲子', '锄头', '梯子', '工具箱'
    ],
    '玩具': [
        '积木', '拼图', '洋娃娃', '遥控车', '机器人', '毛绒玩具',
        '气球', '风筝', '飞盘', '陀螺'
    ],
    
    '植物': [
        '花', '玫瑰', '向日葵', '郁金香', '兰花', '仙人掌', '竹子',
        '树', '松树', '柳树', '枫树', '樱花树', '草', '苔藓'
    ],
    
    '动物': [
        '哺乳动物', '宠物', '野生猫科', '大型食草动物',
        '鱼类', '鸟类', '爬行动物', '两栖动物', '昆虫', '海洋生物'
    ],
    '食物': [
        '甜点', '水果', '蔬菜', '主食', '饮料', '零食'
    ],
    '家具': [
        '沙发', '椅子', '桌子', '床', '柜子'
    ],
    '家居': [
        '家用电器', '厨房用品', '家居装饰', '家具'
    ],
    '交通工具': [
        '轿车', '商用车', '两轮车', '飞机', '船舶', '火车'
    ],
    '电子产品': [
        '智能手机', '电脑', '电脑配件', '相机', '音频设备', '可穿戴设备'
    ],
    '服饰': [
        '上衣', '下装', '鞋子', '配饰', '内衣'
    ],
    '乐器': [
        '弦乐器', '键盘乐器', '打击乐器', '管乐器'
    ],
    '体育用品': [
        '球类运动', '健身器材', '户外运动'
    ],
    '办公用品': [
        '办公文具', '办公设备'
    ],
    '建筑': [
        '住宅建筑', '公共建筑', '桥梁'
    ],
    '自然景观': [
        '山峰', '水域', '森林'
    ],
    '日用品': [
        '化妆用品', '清洁用品', '医疗用品', '工具', '玩具'
    ]
};

const LABEL_TRANSLATIONS = {
    'tench': '丁鱥鱼', 'goldfish': '金鱼',
    'great white shark': '大白鲨', 'tiger shark': '虎鲨',
    'hammerhead': '双髻鲨', 'hammerhead shark': '双髻鲨',
    'electric ray': '电鳐', 'stingray': '黄貂鱼',
    'cock': '公鸡', 'hen': '母鸡', 'ostrich': '鸵鸟',
    'brambling': '燕雀', 'goldfinch': '金翅雀',
    'house finch': '家朱雀', 'junco': '灯芯草雀',
    'indigo bunting': '靛蓝彩鹀', 'robin': '知更鸟',
    'bulbul': '鹎', 'jay': '松鸦', 'magpie': '喜鹊',
    'chickadee': '山雀', 'water ouzel': '河乌',
    'kite': '鸢', 'bald eagle': '白头海雕',
    'vulture': '秃鹫', 'great grey owl': '大灰猫头鹰',
    'european fire salamander': '火蝾螈', 'common newt': '普通蝾螈',
    'eft': '水螈', 'spotted salamander': '斑点钝口螈',
    'axolotl': '墨西哥钝口螈', 'bullfrog': '牛蛙',
    'tree frog': '树蛙', 'tailed frog': '尾蟾',
    'loggerhead': '蠵龟', 'leatherback turtle': '棱皮龟',
    'mud turtle': '泥龟', 'terrapin': '水龟',
    'box turtle': '箱龟', 'banded gecko': '带纹壁虎',
    'common iguana': '绿鬣蜥', 'american chameleon': '安乐蜥',
    'whiptail': '鞭尾蜥', 'agama': '鬣蜥',
    'frilled lizard': '伞蜥', 'alligator lizard': '侧褶蜥',
    'gila monster': '希拉毒蜥', 'green lizard': '绿蜥蜴',
    'african chameleon': '非洲变色龙',
    'komodo dragon': '科莫多龙', 'african crocodile': '非洲鳄',
    'american alligator': '美国短吻鳄', 'triceratops': '三角龙',
    'thunder snake': '雷蛇', 'ringneck snake': '环颈蛇',
    'hognose snake': '猪鼻蛇', 'green snake': '绿蛇',
    'king snake': '王蛇', 'garter snake': '束带蛇',
    'water snake': '水蛇', 'vine snake': '藤蛇',
    'night snake': '夜蛇', 'boa constrictor': '红尾蚺',
    'rock python': '岩蟒', 'indian cobra': '印度眼镜蛇',
    'green mamba': '绿曼巴', 'sea snake': '海蛇',
    'horned viper': '角蝰', 'diamondback': '菱背响尾蛇',
    'sidewinder': '侧进蛇', 'trilobite': '三叶虫',
    'harvestman': '盲蛛', 'daddy longlegs': '长腿蜘蛛',
    'scorpion': '蝎子', 'black and gold garden spider': '金园蛛',
    'barn spider': '谷仓蜘蛛', 'garden spider': '园蛛',
    'black widow': '黑寡妇', 'tarantula': '狼蛛',
    'wolf spider': '狼蛛', 'tick': '蜱虫',
    'centipede': '蜈蚣', 'black grouse': '黑松鸡',
    'ptarmigan': '雷鸟', 'ruffed grouse': '披肩榛鸡',
    'prairie chicken': '草原松鸡', 'peacock': '孔雀',
    'quail': '鹌鹑', 'partridge': '山鹑',
    'african grey': '非洲灰鹦鹉', 'macaw': '金刚鹦鹉',
    'sulphur-crested cockatoo': '葵花凤头鹦鹉',
    'lorikeet': '吸蜜鹦鹉', 'coucal': '鸦鹃',
    'bee eater': '蜂虎', 'hornbill': '犀鸟',
    'hummingbird': '蜂鸟', 'jacamar': '鹟鴷',
    'toucan': '巨嘴鸟', 'drake': '公鸭',
    'red-breasted merganser': '红胸秋沙鸭',
    'goose': '鹅', 'black swan': '黑天鹅',
    'tusker': '象', 'echidna': '针鼹',
    'platypus': '鸭嘴兽', 'wallaby': '沙袋鼠',
    'koala': '考拉', 'wombat': '袋熊',
    'jellyfish': '水母', 'sea anemone': '海葵',
    'brain coral': '脑珊瑚', 'flatworm': '扁形虫',
    'nematode': '线虫', 'conch': '海螺',
    'snail': '蜗牛', 'slug': '蛞蝓',
    'sea slug': '海蛞蝓', 'nudibranch': '海兔',
    'chiton': '石鳖', 'chambered nautilus': '鹦鹉螺',
    'dungeness crab': '珍宝蟹', 'rock crab': '岩蟹',
    'fiddler crab': '招潮蟹', 'king crab': '帝王蟹',
    'american lobster': '美洲龙虾', 'spiny lobster': '大螯虾',
    'crayfish': '小龙虾', 'hermit crab': '寄居蟹',
    'isopod': '等足类', 'white stork': '白鹳',
    'black stork': '黑鹳', 'spoonbill': '琵鹭',
    'flamingo': '火烈鸟', 'little blue heron': '小蓝鹭',
    'american egret': '大白鹭', 'bittern': '麻鹬',
    'crane': '鹤', 'limpkin': '秧鹤',
    'european gallinule': '紫水鸡', 'american coot': '美洲骨顶',
    'bustard': '鸨', 'ruddy turnstone': '翻石鹬',
    'red-backed sandpiper': '红背滨鹬', 'redshank': '红脚鹬',
    'dowitcher': '长嘴鹬', 'oystercatcher': '蛎鹬',
    'pelican': '鹈鹕', 'king penguin': '王企鹅',
    'albatross': '信天翁', 'grey whale': '灰鲸',
    'killer whale': '虎鲸', 'dugong': '儒艮',
    'sea lion': '海狮',
    'chihuahua': '吉娃娃', 'japanese spaniel': '日本狆',
    'maltese dog': '马耳他犬', 'pekinese': '北京犬',
    'shih-tzu': '西施犬', 'blenheim spaniel': '布伦海姆猎犬',
    'papillon': '蝴蝶犬', 'toy terrier': '玩具梗',
    'rhodesian ridgeback': '罗得西亚脊背犬',
    'afghan hound': '阿富汗猎犬', 'basset': '巴吉度猎犬',
    'beagle': '比格犬', 'bloodhound': '寻血猎犬',
    'bluetick': '蓝斑猎犬', 'walker hound': '沃克猎犬',
    'english foxhound': '英国猎狐犬', 'redbone': '红河猎犬',
    'borzoi': '猎狼犬', 'irish wolfhound': '爱尔兰猎狼犬',
    'italian greyhound': '意大利灰狗', 'whippet': '惠比特犬',
    'ibizan hound': '伊比赞猎犬', 'norwegian elkhound': '挪威猎麋犬',
    'otterhound': '水獭猎犬', 'saluki': '萨路基猎犬',
    'scottish deerhound': '苏格兰猎鹿犬', 'weimaraner': '威玛猎犬',
    'staffordshire bullterrier': '斯塔福郡斗牛梗',
    'american staffordshire terrier': '美国斯塔福郡梗',
    'bedlington terrier': '贝德灵顿梗', 'border terrier': '边境梗',
    'kerry blue terrier': '凯利蓝梗', 'irish terrier': '爱尔兰梗',
    'norfolk terrier': '诺福克梗', 'norwich terrier': '诺威奇梗',
    'yorkshire terrier': '约克夏梗', 'lakeland terrier': '湖畔梗',
    'sealyham terrier': '西里汉梗', 'airedale': '万能梗',
    'cairn': '凯恩梗', 'australian terrier': '澳大利亚梗',
    'dandie dinmont': '丹迪丁蒙梗', 'boston bull': '波士顿梗',
    'miniature schnauzer': '迷你雪纳瑞', 'giant schnauzer': '巨型雪纳瑞',
    'standard schnauzer': '标准雪纳瑞', 'scotch terrier': '苏格兰梗',
    'tibetan terrier': '西藏梗', 'silky terrier': '丝毛梗',
    'soft-coated wheaten terrier': '爱尔兰软毛梗',
    'west highland white terrier': '西高地白梗', 'lhasa': '拉萨犬',
    'flat-coated retriever': '平毛寻回犬', 'curly-coated retriever': '卷毛寻回犬',
    'golden retriever': '金毛寻回犬', 'labrador retriever': '拉布拉多寻回犬',
    'chesapeake bay retriever': '切萨皮克湾寻回犬',
    'german short-haired pointer': '德国短毛指示犬',
    'vizsla': '维兹拉犬', 'english setter': '英国雪达犬',
    'irish setter': '爱尔兰雪达犬', 'gordon setter': '戈登雪达犬',
    'brittany spaniel': '布列塔尼猎犬', 'clumber': '克伦伯犬',
    'english springer': '英国史宾格犬', 'welsh springer spaniel': '威尔士史宾格犬',
    'cocker spaniel': '可卡犬', 'sussex spaniel': '萨塞克斯猎犬',
    'irish water spaniel': '爱尔兰水猎犬', 'kuvasz': '库瓦兹犬',
    'schipperke': '舒柏奇犬', 'malinois': '马里努阿犬',
    'briard': '伯瑞犬', 'kelpie': '卡尔比犬',
    'komondor': '可蒙犬', 'old english sheepdog': '英国古代牧羊犬',
    'shetland sheepdog': '喜乐蒂牧羊犬', 'collie': '柯利牧羊犬',
    'border collie': '边境牧羊犬', 'bouvier des flandres': '法兰德斯牧牛犬',
    'rottweiler': '罗威纳犬', 'german shepherd': '德国牧羊犬',
    'doberman': '杜宾犬', 'miniature pinscher': '迷你宾莎犬',
    'greater swiss mountain dog': '大瑞士山地犬',
    'bernese mountain dog': '伯恩山犬', 'appenzeller': '阿彭策尔山犬',
    'entlebucher': '恩特雷布赫山犬', 'boxer': '拳师犬',
    'bull mastiff': '斗牛獒', 'tibetan mastiff': '藏獒',
    'french bulldog': '法国斗牛犬', 'great dane': '大丹犬',
    'saint bernard': '圣伯纳犬', 'eskimo dog': '爱斯基摩犬',
    'malamute': '阿拉斯加雪橇犬', 'siberian husky': '西伯利亚雪橇犬',
    'dalmatian': '大麦町犬', 'affenpinscher': '猴头梗',
    'basenji': '巴辛吉犬', 'pug': '巴哥犬',
    'leonberg': '兰伯格犬', 'newfoundland': '纽芬兰犬',
    'great pyrenees': '大白熊犬', 'samoyed': '萨摩耶',
    'pomeranian': '博美犬', 'chow': '松狮犬',
    'keeshond': '荷兰毛狮犬', 'brabancon griffon': '布鲁塞尔格里芬',
    'pembroke': '彭布罗克威尔士柯基', 'cardigan': '卡迪根威尔士柯基',
    'toy poodle': '玩具贵宾', 'miniature poodle': '迷你贵宾',
    'standard poodle': '标准贵宾', 'mexican hairless': '墨西哥无毛犬',
    'timber wolf': '灰狼', 'white wolf': '白狼',
    'red wolf': '红狼', 'coyote': '郊狼',
    'dingo': '澳洲野犬', 'dhole': '豺',
    'african hunting dog': '非洲野犬', 'hyena': '鬣狗',
    'red fox': '红狐', 'kit fox': '敏狐',
    'arctic fox': '北极狐', 'grey fox': '灰狐',
    'tabby': '虎斑猫', 'tiger cat': '虎猫',
    'persian cat': '波斯猫', 'siamese cat': '暹罗猫',
    'egyptian cat': '埃及猫', 'cougar': '美洲狮',
    'lynx': '猞猁', 'leopard': '豹',
    'snow leopard': '雪豹', 'jaguar': '美洲豹',
    'lion': '狮子', 'tiger': '老虎',
    'cheetah': '猎豹', 'brown bear': '棕熊',
    'american black bear': '美洲黑熊', 'ice bear': '北极熊',
    'sloth bear': '懒熊', 'mongoose': '猫鼬',
    'meerkat': '狐獴', 'tiger beetle': '虎甲',
    'ladybug': '瓢虫', 'ground beetle': '步甲',
    'long-horned beetle': '天牛', 'leaf beetle': '叶甲',
    'dung beetle': '蜣螂', 'rhinoceros beetle': '犀金龟',
    'weevil': '象鼻虫', 'fly': '苍蝇',
    'bee': '蜜蜂', 'ant': '蚂蚁',
    'grasshopper': '蝗虫', 'cricket': '蟋蟀',
    'walking stick': '竹节虫', 'cockroach': '蟑螂',
    'mantis': '螳螂', 'cicada': '蝉',
    'leafhopper': '叶蝉', 'lacewing': '草蛉',
    'dragonfly': '蜻蜓', 'damselfly': '豆娘',
    'admiral': '蛱蝶', 'ringlet': '红眼蝶',
    'monarch': '帝王蝶', 'cabbage butterfly': '菜粉蝶',
    'sulphur butterfly': '粉蝶', 'lycaenid': '灰蝶',
    'starfish': '海星', 'sea urchin': '海胆',
    'sea cucumber': '海参', 'wood rabbit': '棉尾兔',
    'hare': '野兔', 'angora': '安哥拉兔',
    'hamster': '仓鼠', 'porcupine': '豪猪',
    'hedgehog': '刺猬', 'fox squirrel': '狐松鼠',
    'marmot': '土拨鼠', 'beaver': '海狸',
    'guinea pig': '豚鼠', 'sorrel': '栗色马',
    'zebra': '斑马', 'hog': '猪',
    'wild boar': '野猪', 'warthog': '疣猪',
    'hippopotamus': '河马', 'ox': '牛',
    'water buffalo': '水牛', 'bison': '野牛',
    'ram': '公羊', 'bighorn': '大角羊',
    'ibex': '北山羊', 'hartebeest': '狷羚',
    'impala': '黑斑羚', 'gazelle': '瞪羚',
    'arabian camel': '单峰驼', 'llama': '羊驼',
    'weasel': '黄鼠狼', 'mink': '水貂',
    'polecat': '艾鼬', 'black-footed ferret': '黑足鼬',
    'otter': '水獭', 'skunk': '臭鼬',
    'badger': '獾', 'armadillo': '犰狳',
    'three-toed sloth': '三趾树懒', 'orangutan': '红毛猩猩',
    'gorilla': '大猩猩', 'chimpanzee': '黑猩猩',
    'gibbon': '长臂猿', 'siamang': '合趾猿',
    'guenon': '长尾猴', 'patas': '赤猴',
    'baboon': '狒狒', 'macaque': '猕猴',
    'langur': '叶猴', 'colobus': '疣猴',
    'proboscis monkey': '长鼻猴', 'marmoset': '狨猴',
    'capuchin': '卷尾猴', 'howler monkey': '吼猴',
    'titi': '伶猴', 'spider monkey': '蜘蛛猴',
    'squirrel monkey': '松鼠猴', 'madagascar cat': '环尾狐猴',
    'indri': '大狐猴', 'indian elephant': '亚洲象',
    'african elephant': '非洲象', 'lesser panda': '小熊猫',
    'giant panda': '大熊猫', 'barracouta': '杖鱼',
    'eel': '鳗鱼', 'coho': '银鲑',
    'rock beauty': '石美人', 'anemone fish': '小丑鱼',
    'sturgeon': '鲟鱼', 'gar': '雀鳝',
    'lionfish': '狮子鱼', 'puffer': '河豚',
    
    'abacus': '算盘', 'abaya': '阿巴亚长袍',
    'academic gown': '学位服', 'accordion': '手风琴',
    'acoustic guitar': '原声吉他', 'aircraft carrier': '航空母舰',
    'airliner': '客机', 'airship': '飞艇',
    'altar': '祭坛', 'ambulance': '救护车',
    'amphibian': '两栖车辆', 'analog clock': '指针式时钟',
    'apiary': '蜂房', 'apron': '围裙',
    'ashcan': '垃圾桶', 'trash can': '垃圾桶',
    'assault rifle': '突击步枪', 'backpack': '背包',
    'bakery': '面包店', 'balance beam': '平衡木',
    'balloon': '气球', 'ballpoint': '圆珠笔',
    'band aid': '创可贴', 'banjo': '班卓琴',
    'bannister': '扶手', 'barbell': '杠铃',
    'barber chair': '理发椅', 'barbershop': '理发店',
    'barn': '谷仓', 'barometer': '气压计',
    'barrel': '桶', 'barrow': '手推车',
    'baseball': '棒球', 'basketball': '篮球',
    'bassinet': '婴儿篮', 'bassoon': '巴松管',
    'bathing cap': '泳帽', 'bath towel': '浴巾',
    'bathtub': '浴缸', 'beach wagon': '旅行车',
    'station wagon': '旅行车', 'beacon': '灯塔',
    'lighthouse': '灯塔', 'beaker': '烧杯',
    'bearskin': '熊皮帽', 'beer bottle': '啤酒瓶',
    'beer glass': '啤酒杯', 'bell cote': '钟楼',
    'bib': '围兜', 'bicycle-built-for-two': '双人自行车',
    'tandem bicycle': '双人自行车', 'bikini': '比基尼',
    'binder': '文件夹', 'binoculars': '双筒望远镜',
    'birdhouse': '鸟屋', 'boathouse': '船屋',
    'bobsled': '雪橇', 'bolo tie': '波洛领带',
    'bonnet': '无边女帽', 'bookcase': '书柜',
    'bookshop': '书店', 'bottlecap': '瓶盖',
    'bow': '弓', 'bow tie': '领结',
    'brass': '黄铜', 'brassiere': '胸罩',
    'bra': '胸罩', 'breakwater': '防波堤',
    'breastplate': '胸甲', 'broom': '扫帚',
    'bucket': '水桶', 'pail': '水桶',
    'buckle': '带扣', 'bulletproof vest': '防弹背心',
    'bullet train': '子弹头列车', 'butcher shop': '肉店',
    'cab': '出租车', 'taxi': '出租车',
    'taxicab': '出租车', 'caldron': '大锅',
    'candle': '蜡烛', 'cannon': '大炮',
    'canoe': '独木舟', 'can opener': '开罐器',
    'cardigan': '开衫', 'car mirror': '汽车后视镜',
    'carousel': '旋转木马', 'carpenter\'s kit': '工具箱',
    'tool kit': '工具箱', 'carton': '纸箱',
    'car wheel': '车轮', 'cash machine': '自动取款机',
    'atm': '自动取款机', 'cassette': '磁带',
    'cassette player': '磁带播放机', 'castle': '城堡',
    'catamaran': '双体船', 'cd player': 'CD播放器',
    'cello': '大提琴', 'cellular telephone': '手机',
    'cell phone': '手机', 'smartphone': '智能手机',
    'chain': '链条', 'chainlink fence': '铁丝网',
    'chain mail': '锁子甲', 'chain saw': '链锯',
    'chainsaw': '链锯', 'chest': '柜子',
    'chiffonier': '五斗柜', 'chime': '风铃',
    'china cabinet': '瓷器柜', 'christmas stocking': '圣诞袜',
    'church': '教堂', 'cinema': '电影院',
    'movie theater': '电影院', 'cleaver': '切肉刀',
    'cliff dwelling': '崖居', 'cloak': '斗篷',
    'clog': '木屐', 'cocktail shaker': '鸡尾酒摇壶',
    'coffee mug': '咖啡杯', 'coffeepot': '咖啡壶',
    'coil': '线圈', 'combination lock': '密码锁',
    'computer keyboard': '键盘', 'keypad': '键盘',
    'confectionery': '糖果店', 'container ship': '集装箱船',
    'convertible': '敞篷车', 'corkscrew': '开瓶器',
    'cornet': '短号', 'cowboy boot': '牛仔靴',
    'cowboy hat': '牛仔帽', 'cradle': '摇篮',
    'crane': '起重机', 'crash helmet': '安全帽',
    'crate': '板条箱', 'crib': '婴儿床',
    'crock pot': '慢炖锅', 'croquet ball': '槌球',
    'crutch': '拐杖', 'cuirass': '胸甲',
    'dam': '水坝', 'desk': '书桌',
    'desktop computer': '台式电脑', 'dial telephone': '拨号电话',
    'diaper': '尿布', 'digital clock': '数字时钟',
    'digital watch': '电子表', 'dining table': '餐桌',
    'dishrag': '擦碗布', 'dishwasher': '洗碗机',
    'disk brake': '盘式制动器', 'dock': '码头',
    'dogsled': '狗拉雪橇', 'dome': '穹顶',
    'doormat': '门垫', 'drilling platform': '钻井平台',
    'drum': '鼓', 'drumstick': '鼓槌',
    'dumbbell': '哑铃', 'dutch oven': '荷兰烤箱',
    'electric fan': '电风扇', 'electric guitar': '电吉他',
    'electric locomotive': '电力机车', 'entertainment center': '电视柜',
    'envelope': '信封', 'espresso maker': '浓缩咖啡机',
    'face powder': '蜜粉', 'feather boa': '羽毛围巾',
    'file cabinet': '文件柜', 'fireboat': '消防艇',
    'fire engine': '消防车', 'fire truck': '消防车',
    'fire screen': '防火屏', 'flagpole': '旗杆',
    'flute': '长笛', 'folding chair': '折叠椅',
    'football helmet': '橄榄球头盔', 'forklift': '叉车',
    'fountain': '喷泉', 'fountain pen': '钢笔',
    'four-poster': '四帷柱床', 'freight car': '货运车厢',
    'french horn': '圆号', 'frying pan': '平底锅',
    'skillet': '平底锅', 'fur coat': '皮草大衣',
    'garbage truck': '垃圾车', 'gasmask': '防毒面具',
    'gas pump': '加油机', 'goblet': '高脚杯',
    'go-kart': '卡丁车', 'golf ball': '高尔夫球',
    'golfcart': '高尔夫球车', 'gondola': '贡多拉',
    'gong': '锣', 'gown': '礼服',
    'grand piano': '三角钢琴', 'greenhouse': '温室',
    'grille': '格栅', 'grocery store': '杂货店',
    'guillotine': '断头台', 'hair slide': '发夹',
    'hair spray': '发胶', 'half track': '半履带车',
    'hammer': '锤子', 'hamper': '洗衣篮',
    'hand blower': '吹风机', 'hair dryer': '吹风机',
    'hand-held computer': '手持电脑', 'handkerchief': '手帕',
    'hard disc': '硬盘', 'hard disk': '硬盘',
    'harmonica': '口琴', 'harp': '竖琴',
    'harvester': '收割机', 'hatchet': '短斧',
    'holster': '枪套', 'home theater': '家庭影院',
    'honeycomb': '蜂巢', 'hook': '钩子',
    'hoopskirt': '撑裙', 'horizontal bar': '单杠',
    'horse cart': '马车', 'hourglass': '沙漏',
    'ipod': 'iPod', 'iron': '熨斗',
    'smoothing iron': '熨斗', 'jack-o\'-lantern': '南瓜灯',
    'jean': '牛仔裤', 'denim': '牛仔布',
    'jeep': '吉普车', 'jersey': '运动衫',
    't-shirt': 'T恤', 'jigsaw puzzle': '拼图',
    'jinrikisha': '人力车', 'rickshaw': '黄包车',
    'joystick': '游戏手柄', 'kimono': '和服',
    'knee pad': '护膝', 'knot': '结',
    'lab coat': '白大褂', 'ladle': '长柄勺',
    'lampshade': '灯罩', 'laptop': '笔记本电脑',
    'lawn mower': '割草机', 'lens cap': '镜头盖',
    'letter opener': '开信刀', 'library': '图书馆',
    'lifeboat': '救生艇', 'lighter': '打火机',
    'limousine': '豪华轿车', 'limo': '豪华轿车',
    'liner': '邮轮', 'ocean liner': '远洋邮轮',
    'lipstick': '口红', 'loafer': '乐福鞋',
    'lotion': '乳液', 'loudspeaker': '扬声器',
    'speaker': '音箱', 'loupe': '放大镜',
    'lumbermill': '锯木厂', 'sawmill': '锯木厂',
    'magnetic compass': '指南针', 'mailbag': '邮袋',
    'mailbox': '邮箱', 'maillot': '体操服',
    'tank suit': '泳衣', 'manhole cover': '井盖',
    'maraca': '沙锤', 'marimba': '木琴',
    'xylophone': '木琴', 'mask': '面具',
    'matchstick': '火柴', 'maypole': '五月柱',
    'maze': '迷宫', 'measuring cup': '量杯',
    'medicine chest': '药箱', 'megalith': '巨石',
    'microphone': '麦克风', 'microwave': '微波炉',
    'military uniform': '军装', 'milk can': '奶罐',
    'minibus': '中巴', 'miniskirt': '迷你裙',
    'minivan': '面包车', 'missile': '导弹',
    'mitten': '连指手套', 'mixing bowl': '搅拌碗',
    'mobile home': '移动房屋', 'model t': '福特T型车',
    'modem': '调制解调器', 'monastery': '修道院',
    'monitor': '显示器', 'moped': '轻便摩托车',
    'mortar': '迫击炮', 'mortarboard': '学士帽',
    'mosque': '清真寺', 'mosquito net': '蚊帐',
    'motor scooter': '踏板车', 'scooter': '踏板车',
    'mountain bike': '山地车', 'mountain tent': '登山帐篷',
    'mouse': '鼠标', 'computer mouse': '鼠标',
    'mousetrap': '捕鼠器', 'moving van': '搬家车',
    'muzzle': '枪口', 'nail': '钉子',
    'neck brace': '颈托', 'necklace': '项链',
    'nipple': '奶嘴', 'notebook': '笔记本',
    'notebook computer': '笔记本电脑', 'obelisk': '方尖碑',
    'oboe': '双簧管', 'ocarina': '陶笛',
    'odometer': '里程表', 'oil filter': '机油滤清器',
    'organ': '管风琴', 'oscilloscope': '示波器',
    'overskirt': '套裙', 'oxcart': '牛车',
    'oxygen mask': '氧气面罩', 'packet': '小包',
    'paddle': '桨', 'paddlewheel': '明轮',
    'padlock': '挂锁', 'paintbrush': '画笔',
    'pajama': '睡衣', 'palace': '宫殿',
    'panpipe': '排箫', 'paper towel': '纸巾',
    'parachute': '降落伞', 'parallel bars': '双杠',
    'park bench': '公园长椅', 'parking meter': '停车计时器',
    'passenger car': '客车', 'coach': '客车',
    'carriage': '马车', 'patio': '露台',
    'pay-phone': '公用电话', 'pedestal': '底座',
    'plinth': '基座', 'pencil box': '铅笔盒',
    'pencil sharpener': '卷笔刀', 'perfume': '香水',
    'petri dish': '培养皿', 'photocopier': '复印机',
    'pick': '拨片', 'plectrum': '拨片',
    'pickelhaube': '尖顶盔', 'picket fence': '栅栏',
    'pickup': '皮卡车', 'pier': '码头',
    'piggy bank': '存钱罐', 'pill bottle': '药瓶',
    'pillow': '枕头', 'ping-pong ball': '乒乓球',
    'pinwheel': '纸风车', 'pirate': '海盗船',
    'pitcher': '水壶', 'ewer': '水罐',
    'plane': '刨子', 'woodworking plane': '木工刨',
    'planetarium': '天文馆', 'plastic bag': '塑料袋',
    'plate rack': '碗架', 'plow': '犁',
    'plough': '犁', 'plunger': '马桶搋子',
    'polaroid camera': '拍立得', 'pole': '杆子',
    'police van': '警车', 'poncho': '雨披',
    'pool table': '台球桌', 'billiard table': '台球桌',
    'snooker table': '斯诺克球桌', 'pop bottle': '汽水瓶',
    'soda bottle': '汽水瓶', 'pot': '锅',
    'flowerpot': '花盆', 'potter\'s wheel': '陶轮',
    'power drill': '电钻', 'prayer rug': '祈祷毯',
    'printer': '打印机', 'prison': '监狱',
    'projectile': '抛射体', 'projector': '投影仪',
    'puck': '冰球', 'hockey puck': '冰球',
    'punching bag': '沙袋', 'purse': '钱包',
    'quill': '羽毛笔', 'quill pen': '羽毛笔',
    'quilt': '被子', 'comforter': '被子',
    'racer': '赛车', 'race car': '赛车',
    'racing car': '赛车', 'racket': '球拍',
    'racquet': '球拍', 'radiator': '散热器',
    'radio': '收音机', 'radio telescope': '射电望远镜',
    'rain barrel': '雨水桶', 'recreational vehicle': '房车',
    'rv': '房车', 'reel': '卷轴',
    'reflex camera': '反光相机', 'refrigerator': '冰箱',
    'icebox': '冰箱', 'remote control': '遥控器',
    'restaurant': '餐厅', 'revolver': '左轮手枪',
    'rifle': '步枪', 'rocking chair': '摇椅',
    'rotisserie': '旋转烤架', 'rubber eraser': '橡皮',
    'rugby ball': '橄榄球', 'rule': '尺子',
    'ruler': '尺子', 'running shoe': '跑鞋',
    'safe': '保险箱', 'safety pin': '别针',
    'saltshaker': '盐瓶', 'salt shaker': '盐瓶',
    'sandal': '凉鞋', 'sarong': '纱笼',
    'sax': '萨克斯', 'saxophone': '萨克斯管',
    'scabbard': '刀鞘', 'scale': '秤',
    'weighing machine': '秤', 'school bus': '校车',
    'schooner': '纵帆船', 'scoreboard': '记分牌',
    'screen': '屏幕', 'screw': '螺丝',
    'screwdriver': '螺丝刀', 'seat belt': '安全带',
    'seatbelt': '安全带', 'sewing machine': '缝纫机',
    'shield': '盾牌', 'shoe shop': '鞋店',
    'shoji': '障子', 'shopping basket': '购物篮',
    'shopping cart': '购物车', 'shovel': '铲子',
    'shower cap': '浴帽', 'shower curtain': '浴帘',
    'ski': '滑雪板', 'ski mask': '滑雪面罩',
    'sleeping bag': '睡袋', 'slide rule': '计算尺',
    'sliding door': '推拉门', 'slot': '老虎机',
    'snorkel': '潜水通气管', 'snowmobile': '雪地摩托',
    'snowplow': '扫雪机', 'snowplough': '扫雪机',
    'soap dispenser': '皂液器', 'soccer ball': '足球',
    'sock': '袜子', 'solar dish': '太阳灶',
    'solar collector': '太阳能集热器', 'sombrero': '宽边帽',
    'soup bowl': '汤碗', 'space bar': '空格键',
    'space heater': '电暖器', 'space shuttle': '航天飞机',
    'spatula': '锅铲', 'speedboat': '快艇',
    'spider web': '蜘蛛网', 'spindle': '纺锤',
    'sports car': '跑车', 'spotlight': '聚光灯',
    'stage': '舞台', 'steam locomotive': '蒸汽火车',
    'steel arch bridge': '钢拱桥', 'steel drum': '钢鼓',
    'stethoscope': '听诊器', 'stole': '披肩',
    'stone wall': '石墙', 'stopwatch': '秒表',
    'stove': '炉灶', 'strainer': '滤器',
    'streetcar': '有轨电车', 'tram': '有轨电车',
    'trolley': '电车', 'stretcher': '担架',
    'studio couch': '沙发床', 'day bed': '沙发床',
    'stupa': '佛塔', 'submarine': '潜水艇',
    'suit': '西装', 'sundial': '日晷',
    'sunglass': '眼镜', 'sunglasses': '太阳镜',
    'sunscreen': '防晒霜', 'suspension bridge': '悬索桥',
    'swab': '棉签', 'mop': '拖把',
    'sweatshirt': '运动衫', 'swimming trunks': '泳裤',
    'bathing trunks': '泳裤', 'swing': '秋千',
    'switch': '开关', 'syringe': '注射器',
    'table lamp': '台灯', 'tank': '坦克',
    'army tank': '坦克', 'tape player': '磁带播放机',
    'teapot': '茶壶', 'teddy': '泰迪熊',
    'teddy bear': '泰迪熊', 'television': '电视',
    'tv': '电视', 'tennis ball': '网球',
    'thatch': '茅草屋顶', 'theater curtain': '幕布',
    'thimble': '顶针', 'thresher': '打谷机',
    'throne': '王座', 'tile roof': '瓦屋顶',
    'toaster': '烤面包机', 'tobacco shop': '烟草店',
    'toilet seat': '马桶座', 'torch': '火炬',
    'flashlight': '手电筒', 'totem pole': '图腾柱',
    'tow truck': '拖车', 'wrecker': '拖车',
    'toyshop': '玩具店', 'tractor': '拖拉机',
    'trailer truck': '挂车', 'semi': '半挂车',
    'tray': '托盘', 'trench coat': '风衣',
    'tricycle': '三轮车', 'trike': '三轮车',
    'velocipede': '自行车', 'trimaran': '三体船',
    'tripod': '三脚架', 'triumphal arch': '凯旋门',
    'trolleybus': '无轨电车', 'trombone': '长号',
    'tub': '浴缸', 'vat': '大桶',
    'turnstile': '十字转门', 'typewriter keyboard': '打字机键盘',
    'umbrella': '雨伞', 'unicycle': '独轮车',
    'upright': '立式钢琴', 'upright piano': '立式钢琴',
    'vacuum': '吸尘器', 'vacuum cleaner': '吸尘器',
    'vase': '花瓶', 'vault': '拱顶',
    'velvet': '天鹅绒', 'vending machine': '自动售货机',
    'vestment': '祭服', 'viaduct': '高架桥',
    'violin': '小提琴', 'fiddle': '小提琴',
    'volleyball': '排球', 'waffle iron': '华夫饼机',
    'wall clock': '挂钟', 'wallet': '钱包',
    'billfold': '钱包', 'wardrobe': '衣柜',
    'closet': '衣柜', 'warplane': '军机',
    'military plane': '军用飞机', 'washbasin': '洗脸盆',
    'handbasin': '脸盆', 'washer': '洗衣机',
    'washing machine': '洗衣机', 'water bottle': '水瓶',
    'water jug': '水壶', 'water tower': '水塔',
    'whiskey jug': '威士忌酒壶', 'whistle': '哨子',
    'wig': '假发', 'window screen': '窗纱',
    'window shade': '窗帘', 'windsor tie': '温莎领带',
    'wine bottle': '酒瓶', 'wing': '翅膀',
    'wok': '炒锅', 'wooden spoon': '木勺',
    'wool': '羊毛', 'worm fence': '蛇形栅栏',
    'snake fence': '蛇形栅栏', 'wreck': '沉船',
    'yawl': '小帆船', 'yurt': '蒙古包',
    
    'web site': '网站', 'website': '网站',
    'comic book': '漫画书', 'crossword puzzle': '填字游戏',
    'street sign': '路牌', 'traffic light': '红绿灯',
    'traffic signal': '交通信号灯', 'stoplight': '红绿灯',
    'book jacket': '书皮', 'dust cover': '防尘罩',
    'dust jacket': '书皮', 'menu': '菜单',
    'plate': '盘子', 'guacamole': '鳄梨酱',
    'consomme': '清汤', 'hot pot': '火锅',
    'hotpot': '火锅', 'trifle': '奶油蛋糕',
    'ice cream': '冰淇淋', 'icecream': '冰淇淋',
    'ice lolly': '冰棒', 'lolly': '棒棒糖',
    'lollipop': '棒棒糖', 'popsicle': '冰棍',
    'french loaf': '法式面包', 'bagel': '贝果',
    'pretzel': '椒盐卷饼', 'cheeseburger': '芝士汉堡',
    'hotdog': '热狗', 'red hot': '热狗',
    'mashed potato': '土豆泥', 'head cabbage': '卷心菜',
    'broccoli': '西兰花', 'cauliflower': '花椰菜',
    'zucchini': '西葫芦', 'courgette': '西葫芦',
    'spaghetti squash': ' spaghetti南瓜',
    'acorn squash': '橡果南瓜', 'butternut squash': '奶油南瓜',
    'cucumber': '黄瓜', 'cuke': '黄瓜',
    'artichoke': '洋蓟', 'globe artichoke': '洋蓟',
    'bell pepper': '甜椒', 'cardoon': '菜蓟',
    'mushroom': '蘑菇', 'granny smith': '青苹果',
    'strawberry': '草莓', 'orange': '橙子',
    'lemon': '柠檬', 'fig': '无花果',
    'pineapple': '菠萝', 'ananas': '菠萝',
    'banana': '香蕉', 'jackfruit': '菠萝蜜',
    'custard apple': '番荔枝', 'pomegranate': '石榴',
    'hay': '干草', 'carbonara': '培根意面',
    'chocolate sauce': '巧克力酱', 'dough': '面团',
    'meat loaf': '肉糜糕', 'meatloaf': '肉糜糕',
    'pizza': '披萨', 'pizza pie': '披萨',
    'potpie': '馅饼', 'burrito': '墨西哥卷饼',
    'red wine': '红酒', 'espresso': '浓缩咖啡',
    'cup': '杯子', 'eggnog': '蛋酒',
    
    'alp': '高山', 'bubble': '气泡',
    'cliff': '悬崖', 'drop-off': '悬崖',
    'coral reef': '珊瑚礁', 'geyser': '间歇泉',
    'lakeside': '湖边', 'promontory': '海角',
    'headland': '岬角', 'sandbar': '沙洲',
    'seashore': '海边', 'coast': '海岸',
    'valley': '山谷', 'vale': '山谷',
    'volcano': '火山',
    
    'ballplayer': '棒球运动员', 'baseball player': '棒球运动员',
    'groom': '新郎', 'bridegroom': '新郎',
    'scuba diver': '潜水员', 'rapeseed': '油菜籽',
    'daisy': '雏菊', 'yellow lady\'s slipper': '黄花杓兰',
    'corn': '玉米', 'acorn': '橡果',
    'hip': '玫瑰果', 'rose hip': '玫瑰果',
    'buckeye': '七叶树果', 'horse chestnut': '七叶树',
    'conker': '七叶树果', 'coral fungus': '珊瑚菌',
    'agaric': '伞菌', 'gyromitra': '鹿花菌',
    'stinkhorn': '鬼笔菌', 'carrion fungus': '臭角菌',
    'earthstar': '地星菌', 'hen-of-the-woods': '灰树花',
    'bolete': '牛肝菌', 'ear': '穗',
    'spike': '穗', 'capitulum': '头状花序',
    'toilet tissue': '卫生纸', 'toilet paper': '卫生纸',
    'bathroom tissue': '卫生纸'
};

class LabelMapper {
    constructor(options = {}) {
        this.hierarchy = CATEGORY_HIERARCHY;
        this.translations = LABEL_TRANSLATIONS;
        this.standardTranslations = options.standardTranslations || null;
        this.confidenceThreshold = options.confidenceThreshold || 0.05;
        this.topN = options.topN || 5;
        
        console.log('LabelMapper 初始化完成');
        console.log('标准映射表已加载:', this.standardTranslations ? '是' : '否');
        console.log('置信度阈值:', this.confidenceThreshold);
    }

    mapLabels(predictions, options = {}) {
        const threshold = options.confidenceThreshold || this.confidenceThreshold;
        const topN = options.topN || this.topN;
        
        console.log(`\n========== LabelMapper.mapLabels ==========`);
        console.log(`参数：置信度阈值 = ${(threshold * 100).toFixed(0)}%，Top-N = ${topN}`);
        console.log(`输入预测数量：${predictions.length}`);
        
        if (predictions.length === 0) {
            console.log('警告：没有输入预测');
            return {
                predictions: [],
                tags: [],
                filtered: []
            };
        }
        
        const top1Prediction = predictions[0];
        console.log(`\n========== Top-1 Class ID ==========`);
        console.log(`Top-1 Index: ${top1Prediction.index}`);
        console.log(`Top-1 Probability: ${(top1Prediction.probability * 100).toFixed(4)}%`);
        console.log(`Top-1 Original Class: ${top1Prediction.className}`);
        console.log(`=========================================\n`);
        
        const sortedPredictions = [...predictions].sort((a, b) => b.probability - a.probability);
        
        const filtered = this.filterByConfidence(sortedPredictions, threshold);
        console.log(`置信度过滤后：保留 ${filtered.length} / ${predictions.length} 个预测`);
        
        if (filtered.length > 0) {
            console.log('过滤后的预测：');
            filtered.forEach((pred, i) => {
                console.log(`  ${i + 1}. [${pred.index}] ${(pred.probability * 100).toFixed(2)}% - ${pred.className}`);
            });
        }
        
        const topPredictions = filtered.slice(0, topN);
        console.log(`取 Top-${topN}：${topPredictions.length} 个`);
        
        const mapped = [];
        
        for (const pred of topPredictions) {
            const classId = pred.className;
            const confidence = pred.probability;
            const classIndex = pred.index;
            
            const chineseLabel = this.translateToChinese(classIndex, classId);
            const categories = this.expandToCategories(chineseLabel, classId);
            
            mapped.push({
                classId: classId,
                classIndex: classIndex,
                label: chineseLabel,
                confidence: confidence,
                categories: categories
            });
        }
        
        const allTags = this.collectAllTags(mapped, threshold);
        
        console.log(`\n========== 映射结果 ==========`);
        console.log(`预测数量：${mapped.length}`);
        console.log(`标签数量：${allTags.length}`);
        console.log(`========================================\n`);
        
        return {
            predictions: mapped,
            tags: allTags,
            filtered: filtered
        };
    }

    filterByConfidence(predictions, threshold) {
        return predictions.filter(pred => pred.probability >= threshold);
    }

    translateToChinese(classIndex, englishLabel) {
        console.log(`  翻译: Index=${classIndex}, "${englishLabel}"`);
        
        const indexKey = String(classIndex);
        if (this.standardTranslations && this.standardTranslations[indexKey]) {
            const result = this.standardTranslations[indexKey];
            console.log(`    标准映射表匹配: Index ${classIndex} -> "${result}"`);
            return result;
        }
        
        console.log(`    标准映射表未找到，使用备用翻译方法`);
        
        const lowerLabel = englishLabel.toLowerCase();
        const synonyms = lowerLabel.split(',').map(s => s.trim());
        
        const sortedKeys = Object.keys(this.translations).sort((a, b) => b.length - a.length);
        
        for (const key of sortedKeys) {
            const lowerKey = key.toLowerCase();
            for (const synonym of synonyms) {
                if (synonym.includes(lowerKey) || lowerKey.includes(synonym)) {
                    const result = this.translations[key];
                    console.log(`    备用匹配: "${key}" -> "${result}"`);
                    return result;
                }
            }
        }
        
        const firstPart = englishLabel.split(',')[0].trim();
        console.log(`    未找到匹配，返回: "${firstPart}"`);
        return firstPart;
    }

    expandToCategories(chineseLabel, originalLabel) {
        const categories = new Set();
        const lowerOriginal = originalLabel.toLowerCase();
        const lowerChinese = chineseLabel.toLowerCase();
        
        const directCategories = new Set();
        for (const [category, keywords] of Object.entries(this.hierarchy)) {
            if (keywords.some(keyword => 
                lowerOriginal.includes(keyword.toLowerCase()) || 
                lowerChinese.includes(keyword.toLowerCase())
            )) {
                directCategories.add(category);
            }
        }
        
        for (const cat of directCategories) {
            categories.add(cat);
            
            const parentCategories = this.findParentCategories(cat);
            for (const parent of parentCategories) {
                categories.add(parent);
            }
        }
        
        const additionalCats = this.detectCategoriesByKeywords(lowerOriginal, lowerChinese);
        for (const cat of additionalCats) {
            categories.add(cat);
            const parentCategories = this.findParentCategories(cat);
            for (const parent of parentCategories) {
                categories.add(parent);
            }
        }
        
        return Array.from(categories);
    }

    findParentCategories(category) {
        const parents = new Set();
        
        for (const [parentCategory, children] of Object.entries(this.hierarchy)) {
            if (children.includes(category)) {
                parents.add(parentCategory);
                
                const grandParents = this.findParentCategories(parentCategory);
                for (const gp of grandParents) {
                    parents.add(gp);
                }
            }
        }
        
        return Array.from(parents);
    }

    detectCategoriesByKeywords(lowerOriginal, lowerChinese) {
        const categories = new Set();
        
        const keywordMap = {
            '动物': ['dog', 'cat', 'horse', 'cow', 'sheep', 'pig', 'rabbit', 'bear', 'elephant',
                     'giraffe', 'rhinoceros', 'hippopotamus', 'zebra', 'lion', 'tiger', 'leopard',
                     'jaguar', 'cheetah', 'wolf', 'fox', 'monkey', 'chimpanzee', 'gorilla',
                     'kangaroo', 'koala', 'sloth', 'whale', 'dolphin', 'seal', 'fish', 'shark',
                     'bird', 'eagle', 'owl', 'peacock', 'penguin', 'lizard', 'snake', 'turtle',
                     'crocodile', 'frog', 'insect', 'butterfly', 'bee', 'spider', 'scorpion',
                     'hen', 'cock', 'ostrich', 'duck', 'goose', 'squirrel', 'hamster', 'hedgehog',
                     'beaver', 'marmot', 'llama', 'weasel', 'otter', 'badger', 'armadillo',
                     'panda', 'camel', 'deer', 'goat', 'donkey'],
            '家具': ['couch', 'sofa', 'chair', 'armchair', 'table', 'desk', 'bed', 'wardrobe',
                     'bookcase', 'bookshelf', 'cabinet', 'chiffonier', 'table lamp', 'lamp',
                     'coffee table', 'nightstand', 'night stand', 'dresser', 'chest', 'ottoman'],
            '食物': ['hamburger', 'hotdog', 'pizza', 'ice cream', 'cake', 'bread', 'fruit',
                     'vegetable', 'coffee', 'wine', 'chocolate', 'cookie', 'candy', 'pasta',
                     'rice', 'noodle', 'soup', 'steak', 'salad', 'cheese', 'milk', 'egg',
                     'burrito', 'sushi', 'donut', 'bagel', 'sandwich'],
            '电子产品': ['phone', 'computer', 'laptop', 'monitor', 'keyboard', 'mouse',
                         'camera', 'tv', 'television', 'radio', 'speaker', 'headphone',
                         'printer', 'microwave', 'refrigerator', 'washer', 'dishwasher',
                         'tablet', 'ipad', 'smartphone'],
            '交通工具': ['car', 'truck', 'bus', 'train', 'airplane', 'ship', 'boat',
                         'bicycle', 'motorcycle', 'helicopter', 'submarine', 'rocket'],
            '服饰': ['shirt', 't-shirt', 'jeans', 'pants', 'skirt', 'dress', 'coat',
                     'jacket', 'shoe', 'boot', 'hat', 'scarf', 'tie', 'glasses',
                     'sunglasses', 'glove', 'watch', 'necklace', 'wallet', 'bag', 'backpack'],
            '建筑': ['building', 'house', 'castle', 'church', 'bridge', 'tower',
                     'palace', 'monument', 'stadium', 'airport', 'station']
        };
        
        for (const [category, keywords] of Object.entries(keywordMap)) {
            if (keywords.some(keyword => lowerOriginal.includes(keyword))) {
                categories.add(category);
            }
        }
        
        return Array.from(categories);
    }

    collectAllTags(mappedPredictions, threshold) {
        const tags = new Set();
        
        const categoryTags = new Set();
        const specificTags = new Set();
        
        for (const pred of mappedPredictions) {
            if (pred.confidence >= threshold) {
                specificTags.add(pred.label);
            }
            
            for (const category of pred.categories) {
                categoryTags.add(category);
            }
        }
        
        for (const cat of categoryTags) {
            tags.add(cat);
        }
        for (const spec of specificTags) {
            tags.add(spec);
        }
        
        return Array.from(tags);
    }

    isAnimal(label) {
        const animalKeywords = [
            'dog', 'cat', 'horse', 'cow', 'sheep', 'pig', 'rabbit', 'bear', 'elephant',
            'giraffe', 'rhinoceros', 'hippopotamus', 'zebra', 'lion', 'tiger', 'leopard',
            'jaguar', 'cheetah', 'wolf', 'fox', 'monkey', 'chimpanzee', 'gorilla',
            'kangaroo', 'koala', 'sloth', 'whale', 'dolphin', 'seal', 'fish', 'shark',
            'bird', 'eagle', 'owl', 'peacock', 'penguin', 'lizard', 'snake', 'turtle',
            'crocodile', 'frog', 'insect', 'butterfly', 'bee', 'spider', 'scorpion',
            'hen', 'cock', 'ostrich', 'duck', 'goose', 'squirrel', 'hamster', 'hedgehog',
            'beaver', 'marmot', 'llama', 'weasel', 'otter', 'badger', 'armadillo',
            'panda', 'camel', 'deer', 'goat', 'donkey', 'hamster', 'ferret'
        ];
        const lower = label.toLowerCase();
        return animalKeywords.some(keyword => lower.includes(keyword));
    }

    isFurniture(label) {
        const furnitureKeywords = [
            'couch', 'sofa', 'chair', 'armchair', 'table', 'desk', 'bed', 'wardrobe',
            'bookcase', 'bookshelf', 'cabinet', 'chiffonier', 'table lamp', 'lamp',
            'coffee table', 'nightstand', 'night stand', 'dresser', 'chest', 'ottoman',
            'stool', 'bench', 'dining table', 'sideboard', 'hutch', 'display cabinet'
        ];
        const lower = label.toLowerCase();
        return furnitureKeywords.some(keyword => lower.includes(keyword));
    }

    isFood(label) {
        const foodKeywords = [
            'hamburger', 'hotdog', 'pizza', 'ice cream', 'cake', 'bread', 'fruit',
            'vegetable', 'coffee', 'wine', 'beer', 'juice', 'chocolate', 'cookie',
            'candy', 'pasta', 'rice', 'noodle', 'soup', 'steak', 'salad', 'cheese',
            'milk', 'egg', 'burrito', 'sushi', 'donut', 'bagel', 'sandwich',
            'strawberry', 'orange', 'apple', 'banana', 'lemon', 'pineapple'
        ];
        const lower = label.toLowerCase();
        return foodKeywords.some(keyword => lower.includes(keyword));
    }

    getLabelByClassId(classId) {
        if (classId >= 0 && classId < IMAGENET_LABELS.length) {
            return IMAGENET_LABELS[classId];
        }
        return 'unknown';
    }
}

export { LabelMapper, IMAGENET_LABELS, CATEGORY_HIERARCHY };
