# Generated by Django 4.2.7 on 2026-05-03 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="ocr/requests/%Y/%m/", verbose_name="上传文件"
                    ),
                ),
                ("file_name", models.CharField(max_length=200, verbose_name="文件名")),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "ocr_engine",
                    models.CharField(
                        choices=[
                            ("paddleocr", "PaddleOCR"),
                            ("tesseract", "Tesseract"),
                        ],
                        default="paddleocr",
                        max_length=20,
                        verbose_name="OCR引擎",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="ch", max_length=20, verbose_name="识别语言"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始处理时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_requests",
                        to="contracts.contractdocument",
                        verbose_name="合同文档",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR请求",
                "verbose_name_plural": "OCR请求管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="原始识别文本"
                    ),
                ),
                (
                    "processed_text",
                    models.TextField(blank=True, null=True, verbose_name="处理后文本"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="置信度",
                    ),
                ),
                (
                    "processing_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="处理时间(秒)",
                    ),
                ),
                (
                    "extracted_fields",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="提取的字段"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ocr_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="ocr_service.ocrrequest",
                        verbose_name="OCR请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR结果",
                "verbose_name_plural": "OCR结果管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OCRTextLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="识别文本")),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="置信度"
                    ),
                ),
                ("bbox", models.JSONField(default=list, verbose_name="边界框坐标")),
                ("line_number", models.IntegerField(default=0, verbose_name="行号")),
                ("page_number", models.IntegerField(default=1, verbose_name="页码")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_lines",
                        to="ocr_service.ocrresult",
                        verbose_name="OCR结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR文本行",
                "verbose_name_plural": "OCR文本行管理",
                "ordering": ["page_number", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedContractField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("contract_number", "合同编号"),
                            ("landlord_name", "房东姓名"),
                            ("landlord_phone", "房东电话"),
                            ("landlord_id_card", "房东身份证号"),
                            ("tenant_name", "房客姓名"),
                            ("tenant_phone", "房客电话"),
                            ("tenant_id_card", "房客身份证号"),
                            ("property_address", "房屋地址"),
                            ("start_date", "开始日期"),
                            ("end_date", "结束日期"),
                            ("monthly_rent", "月租金"),
                            ("deposit", "押金"),
                            ("payment_method", "付款方式"),
                            ("payment_day", "付款日"),
                            ("water_price", "水费单价"),
                            ("electricity_price", "电费单价"),
                            ("gas_price", "燃气费单价"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="字段名称"),
                ),
                ("field_value", models.TextField(verbose_name="字段值")),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="置信度"
                    ),
                ),
                (
                    "source_text",
                    models.TextField(blank=True, null=True, verbose_name="源文本"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="验证时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_fields",
                        to="ocr_service.ocrresult",
                        verbose_name="OCR结果",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_fields",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="验证人",
                    ),
                ),
            ],
            options={
                "verbose_name": "提取的合同字段",
                "verbose_name_plural": "提取的合同字段管理",
                "ordering": ["created_at"],
            },
        ),
    ]
